<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Margherita Calderan">
<meta name="author" content="Filippo Gambarota">
<meta name="author" content="Livio Finos">
<meta name="author" content="Gianmarco Altoè">
<meta name="keywords" content="probability of direction, multiple testing, prior-odds, FDR">
<meta name="description" content="PROBABILITY OF DIRECTION AND MULTIPLICITY">

<title>A Prior-Odds Adjustment for the Probability of Direction in Multiple Testing</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="manuscript_files/libs/clipboard/clipboard.min.js"></script>
<script src="manuscript_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="manuscript_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="manuscript_files/libs/quarto-html/popper.min.js"></script>
<script src="manuscript_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="manuscript_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="manuscript_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="manuscript_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="manuscript_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="manuscript_files/libs/bootstrap/bootstrap-7f4bd21cce89c3c347010089e22c3a79.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="_extensions/wjschne/apaquarto/apa.css">
</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#firstheader" id="toc-firstheader" class="nav-link active" data-scroll-target="#firstheader">A Prior-Odds Adjustment for the Probability of Direction in Multiple Testing</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#probability-of-direction" id="toc-probability-of-direction" class="nav-link" data-scroll-target="#probability-of-direction">Probability of direction</a></li>
  <li><a href="#multiplicity-problem" id="toc-multiplicity-problem" class="nav-link" data-scroll-target="#multiplicity-problem">Multiplicity problem</a>
  <ul class="collapse">
  <li><a href="#from-posterior-probabilities-to-posterior-odds" id="toc-from-posterior-probabilities-to-posterior-odds" class="nav-link" data-scroll-target="#from-posterior-probabilities-to-posterior-odds">From posterior probabilities to posterior odds</a></li>
  <li><a href="#multiplicity-adjustment-via-prior-odds" id="toc-multiplicity-adjustment-via-prior-odds" class="nav-link" data-scroll-target="#multiplicity-adjustment-via-prior-odds">Multiplicity adjustment via prior odds</a></li>
  <li><a href="#error-rates-under-the-prior-odds-adjustment" id="toc-error-rates-under-the-prior-odds-adjustment" class="nav-link" data-scroll-target="#error-rates-under-the-prior-odds-adjustment">Error rates under the prior-odds adjustment</a>
  <ul class="collapse">
  <li><a href="#simulation-study" id="toc-simulation-study" class="nav-link" data-scroll-target="#simulation-study">Simulation Study</a></li>
  <li><a href="#comparison-with-other-bayesian-methods" id="toc-comparison-with-other-bayesian-methods" class="nav-link" data-scroll-target="#comparison-with-other-bayesian-methods">Comparison with other Bayesian methods</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#application-worked-example-with-the-r-package-multibayes" id="toc-application-worked-example-with-the-r-package-multibayes" class="nav-link" data-scroll-target="#application-worked-example-with-the-r-package-multibayes">Application: worked example with the R Package <code>multibayes</code></a></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a>
  <ul class="collapse">
  <li><a href="#author-contributions" id="toc-author-contributions" class="nav-link" data-scroll-target="#author-contributions">Author Contributions</a></li>
  <li><a href="#conflicts-of-interest" id="toc-conflicts-of-interest" class="nav-link" data-scroll-target="#conflicts-of-interest">Conflicts of Interest</a></li>
  <li><a href="#acknowledgments" id="toc-acknowledgments" class="nav-link" data-scroll-target="#acknowledgments">Acknowledgments</a></li>
  <li><a href="#prior-versions" id="toc-prior-versions" class="nav-link" data-scroll-target="#prior-versions">Prior Versions</a></li>
  <li><a href="#open-materials" id="toc-open-materials" class="nav-link" data-scroll-target="#open-materials">Open Materials</a></li>
  </ul></li>
  <li><a href="#refs" id="toc-refs" class="nav-link" data-scroll-target="#refs">References</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="../manuscript.pdf"><i class="bi bi-file-pdf"></i>PDF (apaquarto)</a></li><li><a href="manuscript.docx"><i class="bi bi-file-word"></i>MS Word (apaquarto)</a></li></ul></div></nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content" id="quarto-document-content">

<!-- This file is intentionally empty. The APA title page for HTML output
     is generated by frontmatter.lua. Do not add content here — it would
     override the Lua-generated title block. -->


<br>

<br>

<section id="title" class="level1 title unnumbered unlisted">
<h1 class="title unnumbered unlisted">A Prior-Odds Adjustment for the Probability of Direction in Multiple Testing</h1>
<div class="Author">
<br>

<p>Margherita Calderan<sup>1,2</sup>, Filippo Gambarota<sup>1</sup>, Livio Finos<sup>3,4</sup>, and Gianmarco Altoè<sup>1</sup></p>
<p><sup>1</sup>Department of Developmental Psychology and Socialization, University of Padova</p>
<p><sup>2</sup>Department of General Psychology, University of Padova</p>
<p><sup>3</sup>Department of Statistical Sciences, University of Padova</p>
<p><sup>4</sup>Padova Neuroscience Center, University of Padova</p>
</div>
<p>Margherita Calderan <img src="_extensions/wjschne/apaquarto/ORCID-iD_icon-vector.svg" id="orcid" class="img-fluid" style="width:4.23mm" alt="Orcid ID Logo: A green circle with white letters ID"> <a href="https://orcid.org/0009-0005-5668-5162">https://orcid.org/0009-0005-5668-5162</a></p>
<p>Filippo Gambarota <img src="_extensions/wjschne/apaquarto/ORCID-iD_icon-vector.svg" id="orcid" class="img-fluid" style="width:4.23mm" alt="Orcid ID Logo: A green circle with white letters ID"> <a href="https://orcid.org/0000-0002-6666-1747">https://orcid.org/0000-0002-6666-1747</a></p>
<p>Livio Finos <img src="_extensions/wjschne/apaquarto/ORCID-iD_icon-vector.svg" id="orcid" class="img-fluid" style="width:4.23mm" alt="Orcid ID Logo: A green circle with white letters ID"> <a href="https://orcid.org/0000-0003-3181-8078">https://orcid.org/0000-0003-3181-8078</a></p>
<p>Gianmarco Altoè <img src="_extensions/wjschne/apaquarto/ORCID-iD_icon-vector.svg" id="orcid" class="img-fluid" style="width:4.23mm" alt="Orcid ID Logo: A green circle with white letters ID"> <a href="https://orcid.org/0000-0003-1154-9528">https://orcid.org/0000-0003-1154-9528</a></p>
<p>Author roles were classified using the Contributor Role Taxonomy (CRediT; https://credit.niso.org/) as follows: <em>Margherita Calderan</em><strong>: </strong>conceptualization, methodology, software, visualization, and writing – original draft. <em>Filippo Gambarota</em><strong>: </strong>methodology, software, and writing – review &amp; editing. <em>Livio Finos</em><strong>: </strong>supervision, methodology, and writing – review &amp; editing. <em>Gianmarco Altoè</em><strong>: </strong>supervision, conceptualization, and writing – review &amp; editing</p>
<p>Correspondence concerning this article should be addressed to Margherita Calderan, Department of Developmental Psychology and Socialization, University of Padova, Via Venezia 8, Padova 35131, Italy, Email: <a href="mailto:margherita.calderan@unipd.it">margherita.calderan@unipd.it</a></p>
<br>
</section>
<section id="abstract" class="level1 unnumbered unlisted AuthorNote">
<h1 class="unnumbered unlisted AuthorNote">Abstract</h1>
<div class="AbstractFirstParagraph">
<p>The probability of direction (<span class="math inline">pd</span>) has seen rapid adoption in psychological research as an intuitive posterior summary that quantifies how strongly the posterior distribution favors one direction of an effect over the other. In practice, researchers often turn <span class="math inline">pd</span> into a binary decision rule by applying fixed thresholds (e.g., <span class="math inline">pd&gt;0.975</span>), declaring evidence for an effect when posterior mass concentrates strongly on one side. When this rule is applied across many parameters, it can substantially increase the risk of misleading conclusions. We argue that this problem stems from neglecting the prior probability that for every tested effect, the data-favored direction does not reflect a genuine effect. This quantity, often left implicit, becomes increasingly consequential as the number of tested effects grows. To address this, we propose a prior-odds adjustment to <span class="math inline">pd</span> that requires researchers to explicitly specify the proportion of tested effects they expect to be null. The adjustment accounts for multiplicity without modifying the model used in parameter estimation, offers a transparent mechanism for incorporating prior skepticism about the existence of effects, and reduces the risk of false discoveries in multi-parameter settings. We evaluate its behavior through simulation across varying sample sizes and proportions of null effects, and provide an R package to facilitate applied use.</p>
</div>
<p><em>Keywords</em>: probability of direction, multiple testing, prior-odds, FDR</p>
<br>
</section>
<section id="firstheader" class="level1 title unnumbered">
<h1 class="title unnumbered">A Prior-Odds Adjustment for the Probability of Direction in Multiple Testing</h1>
<div style="page-break-after: always;"></div>
</section>
<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>Over the past two decades, the use of Bayesian methods in psychological research has grown considerably <span class="citation" data-cites="Van2017 Jevremov2024 Pfadt2025">(<a href="#ref-Jevremov2024" role="doc-biblioref">Jevremov &amp; Pajić, 2024</a>; <a href="#ref-Pfadt2025" role="doc-biblioref">Pfadt et al., 2025</a>; <a href="#ref-Van2017" role="doc-biblioref">Van De Schoot et al., 2017</a>)</span>. This expansion has, however, been accompanied by practices reminiscent of the “null ritual” in frequentist statistics, where widespread adoption gave way to automatic application rather than principled reasoning <span class="citation" data-cites="Gigerenzer2004 Cohen1994">(<a href="#ref-Cohen1994" role="doc-biblioref">Cohen, 1994</a>; <a href="#ref-Gigerenzer2004" role="doc-biblioref">Gigerenzer, 2004</a>)</span>. Researchers sometimes treat Bayes Factor thresholds (e.g., BF &gt; 3) as dichotomous decision rules, or claim that an effect “exists” because the posterior probability of a directional effect exceeds a conventional benchmark such as 95% <span class="citation" data-cites="Heck2023 Kelter2023 Tendeiro2024 Hoijtink2016 Tendeiro2019 Kruschke2018">(<a href="#ref-Heck2023" role="doc-biblioref">Heck et al., 2023</a>; <a href="#ref-Hoijtink2016" role="doc-biblioref">Hoijtink et al., 2016</a>; <a href="#ref-Kelter2023" role="doc-biblioref">Kelter, 2023</a>; <a href="#ref-Kruschke2018" role="doc-biblioref">Kruschke, 2018</a>; <a href="#ref-Tendeiro2024" role="doc-biblioref">Tendeiro et al., 2024</a>; <a href="#ref-Tendeiro2019" role="doc-biblioref">Tendeiro &amp; Kiers, 2019</a>)</span>. Such cutoffs are convenient, but they encourage all-or-none interpretations, and when these binary judgments are applied repeatedly across many parameters they generate a multiplicity problem no different in kind from the one long recognized in frequentist statistics.</p>
<p>Frequentists developed methods to address this problem, controlling either the Family-Wise Error Rate (FWER; the probability of at least one false positive) or the False Discovery Rate (FDR; the expected proportion of false positives among rejected hypotheses) <span class="citation" data-cites="Benjamini1995 Westfall1993">(<a href="#ref-Benjamini1995" role="doc-biblioref">Benjamini &amp; Hochberg, 1995</a>; <a href="#ref-Westfall1993" role="doc-biblioref">Westfall &amp; Young, 1993</a>)</span>. These procedures address whether a spurious result enters the literature, but leave unresolved a subtler consequence of the same selection process. When researchers examine many parameters but highlight only the most extreme estimates, selection systematically inflates reported magnitudes <span class="citation" data-cites="Gelman2014 Zwet2021 Altoe2020">(<a href="#ref-Altoe2020" role="doc-biblioref">Altoè et al., 2020</a>; <a href="#ref-Gelman2014" role="doc-biblioref">Gelman &amp; Carlin, 2014</a>; <a href="#ref-Zwet2021" role="doc-biblioref">Zwet &amp; Cator, 2021</a>)</span>. Bayesian methods can mitigate this overestimation, pulling extreme estimates toward more plausible values through informative priors <span class="citation" data-cites="Zwet2022 Dawid1994">(<a href="#ref-Dawid1994" role="doc-biblioref">Dawid, 1994</a>; <a href="#ref-Zwet2022" role="doc-biblioref">Zwet &amp; Gelman, 2022</a>)</span> and hierarchical modeling <span class="citation" data-cites="Gelman2012 GelmanBook Kruschke2011 Berry1999">(<a href="#ref-Berry1999" role="doc-biblioref">Berry &amp; Hochberg, 1999</a>; <a href="#ref-Gelman2012" role="doc-biblioref">Gelman et al., 2012</a>, <a href="#ref-GelmanBook" role="doc-biblioref">2013</a>; <a href="#ref-Kruschke2011" role="doc-biblioref">Kruschke, 2011</a>)</span>. Magnitude bias and false-positive accumulation are, however, distinct problems. Shrinkage offers no guarantee about the error properties of a decision rule applied across many parameters: if the same cutoff is used repeatedly (e.g., declaring an effect whenever a posterior probability exceeds 95%), the probability of spurious findings can remain substantial. Bayesian responses to this issue do exist, such as joint probability statements <span class="citation" data-cites="Gelman2000 Pruzek2016 Schnell2020 Box1992">(<a href="#ref-Box1992" role="doc-biblioref">Box &amp; Tiao, 1992</a>; <a href="#ref-Gelman2000" role="doc-biblioref">Gelman &amp; Tuerlinckx, 2000</a>; <a href="#ref-Pruzek2016" role="doc-biblioref">Pruzek, 2016</a>; <a href="#ref-Schnell2020" role="doc-biblioref">Schnell et al., 2020</a>)</span> or priors over the hypothesis space that scale with the number of tests <span class="citation" data-cites="Scott2006 Scott2010 Jeffreys1938 Westfall1997">(<a href="#ref-Jeffreys1938" role="doc-biblioref">Jeffreys, 1938</a>; <a href="#ref-Scott2006" role="doc-biblioref">Scott &amp; Berger, 2006</a>; <a href="#ref-Scott2010" role="doc-biblioref">Scott &amp; Berger, 2010</a>; <a href="#ref-Westfall1997" role="doc-biblioref">Westfall et al., 1997</a>)</span>.</p>
<p>Here we focus on an increasingly adopted decision rule based on the probability of direction (<span class="math inline">pd</span>) <span class="citation" data-cites="Stone2024 Brissenden2023 Hochman2025 Makowski2020 Brissenden2024 Ciranka2026 Schurr2024 Ben2022 Bramley2022">(<a href="#ref-Ben2022" role="doc-biblioref">Ben-Artzi et al., 2022</a>; <a href="#ref-Bramley2022" role="doc-biblioref">Bramley &amp; Ruggeri, 2022</a>; <a href="#ref-Brissenden2023" role="doc-biblioref">Brissenden et al., 2023</a>, <a href="#ref-Brissenden2024" role="doc-biblioref">2024</a>; <a href="#ref-Ciranka2026" role="doc-biblioref">Ciranka et al., 2026</a>; <a href="#ref-Hochman2025" role="doc-biblioref">Hochman et al., 2025</a>; <a href="#ref-Makowski2020" role="doc-biblioref">Makowski et al., 2020</a>; <a href="#ref-Schurr2024" role="doc-biblioref">Schurr et al., 2024</a>; <a href="#ref-Stone2024" role="doc-biblioref">Stone-Sabali et al., 2024</a>)</span>. The <span class="math inline">pd</span> quantifies the probability that an effect lies in its dominant direction <span class="citation" data-cites="Makowski2019 Shi2021">(<a href="#ref-Makowski2019" role="doc-biblioref">Makowski et al., 2019</a>; <a href="#ref-Shi2021" role="doc-biblioref">Shi &amp; Yin, 2021</a>)</span>; researchers claim evidence for an effect when it exceeds a fixed threshold (e.g., <span class="math inline">pd&gt;0.95</span>, <span class="math inline">pd&gt;0.975</span>). We examine the frequentist operating characteristics<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> of such a rule, and consider how the resulting multiplicity problem can be addressed. Following the second strategy noted above, we propose a prior-odds correction for <span class="math inline">pd</span> grounded in the foundational work of <span class="citation" data-cites="Jeffreys1938 Westfall1997">Jeffreys (<a href="#ref-Jeffreys1938" role="doc-biblioref">1938</a>; see also <a href="#ref-Westfall1997" role="doc-biblioref">Westfall et al., 1997</a>)</span> and more recent Bayesian approaches to FDR control <span class="citation" data-cites="Scott2006 Scott2010 Guo2010 Abraham2022 Efron2001 Storey2003 Storey2002">(<a href="#ref-Abraham2022" role="doc-biblioref">Abraham et al., 2022</a>; <a href="#ref-Efron2001" role="doc-biblioref">Efron et al., 2001</a>; <a href="#ref-Guo2010" role="doc-biblioref">Guo &amp; Heitjan, 2010</a>; <a href="#ref-Scott2006" role="doc-biblioref">Scott &amp; Berger, 2006</a>; <a href="#ref-Scott2010" role="doc-biblioref">Scott &amp; Berger, 2010</a>; <a href="#ref-Storey2002" role="doc-biblioref">Storey, 2002</a>, <a href="#ref-Storey2003" role="doc-biblioref">2003</a>)</span>. The correction requires the researcher to specify the proportion of tested effects expected to be null.</p>
<p>It bears emphasis that the proposed adjustment does not control error rates per se; rather, it makes explicit the prior skepticism the researcher brings to the family of hypotheses, allowing the resulting posterior probability to reflect both the observed data and the researcher’s substantive beliefs about the prevalence of true effects. When those beliefs are well-calibrated to the data-generating process, error rates are naturally reduced as a consequence.</p>
<p>The paper proceeds as follows. We begin by introducing <span class="math inline">pd</span> and examining its use as a test of an effect’s existence, then discuss how prior choice shapes its behavior and why more skeptical within-model priors alone cannot resolve the multiplicity problem. We then develop the prior-odds adjustment, evaluate its properties through simulation, and compare its performance with two others Bayesian multiple comparison procedures. A worked example using the accompanying R package <span class="citation" data-cites="Calderan2026">(<a href="#ref-Calderan2026" role="doc-biblioref">Calderan &amp; Gambarota, 2026</a>)</span> follows, after which we conclude with a general discussion.</p>
</section>
<section id="probability-of-direction" class="level1">
<h1>Probability of direction</h1>
<p>The probability of direction (<span class="math inline">pd</span>) is a posterior summary that quantifies how strongly the posterior distribution favors one direction of an effect relative to a reference (<span class="math inline">\theta_{null}</span>) value <span class="citation" data-cites="Makowski2019">(<a href="#ref-Makowski2019" role="doc-biblioref">Makowski et al., 2019</a>)</span>. For a continuous posterior, it can be defined as the larger of the two one-sided posterior probabilities: <span class="math inline">pd = \max(\Pr(\theta &lt; \theta_{null} \mid y),\ \Pr(\theta &gt; \theta_{null} \mid y)),</span> and it ranges from 0.50 (no directional preference) to 1 (all on one side). The <span class="math inline">pd</span> equals exactly the complement of the one-sided <span class="math inline">p</span>-value when computed on the posterior of a location parameter in exponential-family models estimated under a uniform prior; under a broader class of priors, this correspondence holds approximately <span class="citation" data-cites="Marsman2017 Casella1987 Shi2021">(<a href="#ref-Casella1987" role="doc-biblioref">Casella &amp; Berger, 1987</a>; <a href="#ref-Marsman2017" role="doc-biblioref">Marsman &amp; Wagenmakers, 2017</a>; <a href="#ref-Shi2021" role="doc-biblioref">Shi &amp; Yin, 2021</a>)</span>.</p>
<p>In practice, the <span class="math inline">pd</span> is often used to summarize both the direction and existence of an effect. This interpretation is clearest when phrased as a decision rule <span class="math inline">pd&gt;c</span>: the posterior must assign more than <span class="math inline">c</span> probability mass to the side of <span class="math inline">\theta_{\text{null}}</span> favored by the data. Setting <span class="math inline">c=1-\alpha/2</span> is convenient because it bounds the posterior mass in the opposite tail by <span class="math inline">\alpha/2</span>. For concreteness, suppose the posterior favors a positive effect so that <span class="math inline">pd=\Pr(\theta&gt;0\mid y)</span>. An <span class="math inline">\alpha=0.05</span> implies <span class="math inline">c=0.975</span>, therefore the rule <span class="math inline">pd&gt;c</span> requires that <span class="math inline">\Pr(\theta\le 0 \mid y)&lt;0.025</span>, placing less than 2.5% of posterior mass at or below <span class="math inline">0</span>.</p>
<p>As <a href="#fig-pd-ci" class="quarto-xref" aria-expanded="false">Figure&nbsp;1</a> illustrates, observing <span class="math inline">pd&gt;0.975</span> is equivalent to excluding <span class="math inline">0</span> from the central 95% equi-tailed credible interval. When the credible interval excludes the null value, one can infer that the null is relatively implausible <span class="citation" data-cites="Box1992">(<a href="#ref-Box1992" role="doc-biblioref">Box &amp; Tiao, 1992</a>)</span>. Given these considerations, although <span class="math inline">pd</span> and the frequentist <span class="math inline">p</span>-value target different quantities, it is expected that decision rules of the form <span class="math inline">pd&gt;c</span> approximate the operating characteristics of familiar frequentist rules such as <span class="math inline">p&lt;\alpha</span>.</p>
<p>Although we express the decision threshold as <span class="math inline">c = 1 - \alpha/2</span> (with <span class="math inline">\alpha = 0.05</span>) and set <span class="math inline">\theta_{\text{null}} = 0</span> throughout for ease of exposition, neither choice is restrictive. The threshold <span class="math inline">c</span> can be set to any posterior probability cutoff, and <span class="math inline">\theta_{\text{null}}</span> can take any non-zero value, which is particularly relevant when hypotheses involve a minimum effect of practical interest <span class="citation" data-cites="Lakens2018">(<a href="#ref-Lakens2018" role="doc-biblioref">Lakens et al., 2018</a>)</span>.</p>
</section>
<section id="multiplicity-problem" class="level1">
<h1>Multiplicity problem</h1>
<p>Under the null hypothesis, <span class="math inline">p</span>-values are uniformly distributed on <span class="math inline">[0, 1]</span>. Because <span class="math inline">pd</span> can be mapped to the <span class="math inline">p</span>-value, this implies a corresponding null reference behavior for <span class="math inline">pd</span> on <span class="math inline">[0.5, 1]</span>. However, because <span class="math inline">pd</span> is a posterior probability regarding the sign of <span class="math inline">\theta</span>, its null distribution depends not only on the likelihood but also on how strongly the prior concentrates probability near 0, that is, on how strongly it “expects” near-null effects. To make this concrete, we use a conjugate normal–normal model: the observations are normal with known variance, <span class="math inline">y_i \mid \theta \sim \mathcal{N}(\theta, 1)</span> (with true <span class="math inline">\theta = 0</span>), and the effect carries a mean-zero normal prior, <span class="math inline">\theta \sim \mathcal{N}(0, \tau)</span>, where <span class="math inline">\tau</span> denotes the prior standard deviation. This pairing yields a normal posterior in which the <span class="math inline">\tau</span> governs the degree of skepticism.</p>
<p>Varying the sample size (<span class="math inline">n \in \{30, 50, 100\}</span>) and <span class="math inline">\tau</span> (<span class="math inline">0.2, 0.5, 1, 1.5</span>) shows that the probability that <span class="math inline">pd</span> exceeds 0.975 under the null is not constant (<a href="#fig-uniform-pd" class="quarto-xref" aria-expanded="false">Figure&nbsp;2</a>). Under diffuse priors (<span class="math inline">\tau \geq 1</span>) and/or sufficiently large samples, <span class="math inline">pd</span> recovers the uniform null reference, with constant density on <span class="math inline">[0.5, 1]</span>. A skeptical prior (e.g., <span class="math inline">\tau = 0.2</span>), by contrast, induces shrinkage toward <span class="math inline">0.5</span>, effectively reducing the error rate.</p>
<p>While skeptical priors reduce the probability that a single test yields an extreme <span class="math inline">pd</span>, they do not address the issue that, as the number of tests <span class="math inline">m</span> increases, so does the probability of observing at least one extreme value among <span class="math inline">pd_1, \dots, pd_m</span>. The approach presented below addresses this at the level of the testing procedure rather than the within-model prior, by placing a separate prior on the proportion of effects expected to be null. This lets researchers who use uninformative or weakly informative priors for estimation still incorporate substantive beliefs at the family level.</p>
<p>As we formalize in the next section, the correction operates on the Bayes Factor comparing one directional hypothesis against the other. For <span class="math inline">pd</span> to enter this framework, it must coincide with that Bayes Factor, and this holds only under a specific condition. Because <span class="math inline">pd</span> is the posterior probability mass on one side of <span class="math inline">\theta_{\text{null}}</span>, it maps directly onto the posterior odds between the two directional hypotheses (<span class="math inline">\theta &gt; \theta_{\text{null}}</span> vs.&nbsp;<span class="math inline">\theta &lt; \theta_{\text{null}}</span>). These posterior odds equal the Bayes Factor only when the within-model prior is symmetric around <span class="math inline">\theta_{\text{null}}</span>: symmetry makes the two directions equally plausible a priori, so the prior odds are unity and the posterior odds reduce to the ratio of marginal likelihoods. This requirement is typically satisfied by the default priors in standard Bayesian software, and it remains compatible with any degree of prior information about effect magnitude, which is expressed through <span class="math inline">\theta_{\text{null}}</span>.</p>
<section id="from-posterior-probabilities-to-posterior-odds" class="level2">
<h2 data-anchor-id="from-posterior-probabilities-to-posterior-odds">From posterior probabilities to posterior odds</h2>
<p>To connect <span class="math inline">pd</span> to posterior odds, consider the directional hypotheses <span class="math inline">H_{+}: \theta &gt; 0</span> and <span class="math inline">H_{-}: \theta &lt; 0</span>. These hypotheses partition the parameter space based on the sign of <span class="math inline">\theta</span>. If the prior for <span class="math inline">\theta</span> is continuous and symmetric about 0, then the two directions are equally plausible a priori: <span class="math inline">\Pr(H_{+}) = \Pr(H_{-}) = 0.5</span>. Without loss of generality, assume the posterior favors <span class="math inline">H_{+}</span>, such that <span class="math inline">pd = \Pr(H_{+} \mid y) = \Pr(\theta &gt; 0 \mid y)</span>. The complement is then given by <span class="math inline">1 - pd = \Pr(\theta \le 0 \mid y)</span>. The posterior odds comparing these two hypotheses are therefore: <span class="math display">
\frac{pd}{1 - pd} = \frac{\Pr(H_{+} \mid y)}{\Pr(H_{-0} \mid y)}
</span></p>
<p>For a continuous posterior distribution, the probability of any single value (e.g., <span class="math inline">\Pr(\theta = 0 \mid y)</span>) is 0, which means that one could write <span class="math inline">\frac{pd}{1 - pd} = \frac{\Pr(H_{+} \mid y)}{\Pr(H_{-} \mid y)}</span>. However, we retain the notation <span class="math inline">H_{-0}</span> in the denominator to explicitly indicate that the hypothesis includes the point null value of zero. Applying Bayes’ rule, these posterior odds can be decomposed into a Bayes Factor and prior odds: <span class="math display">
\frac{\Pr(H_{+} \mid y)}{\Pr(H_{-0} \mid y)} = \text{BF}_{+/-0} \times \frac{\Pr(H_{+})}{\Pr(H_{-0})}
</span> where <span class="math inline">\text{BF}_{+/-0}</span> quantifies the relative likelihood of the data under <span class="math inline">H_{+}</span> versus <span class="math inline">H_{-0}</span>. Under prior symmetry, <span class="math inline">\frac{\Pr(H_{+})}{\Pr(H_{-0})} = 1</span>, which yields <span class="math inline">\frac{pd}{1 - pd} = \text{BF}_{+/-0}</span> <span class="citation" data-cites="Marsman2017">(<a href="#ref-Marsman2017" role="doc-biblioref">Marsman &amp; Wagenmakers, 2017</a>)</span>. Thus, the odds <span class="math inline">\frac{pd}{1 - pd}</span> computed from posterior draws can be interpreted directly as evidence favoring <span class="math inline">\theta &gt; 0</span> over <span class="math inline">\theta \le 0</span> (or <span class="math inline">\theta &lt; 0</span> over <span class="math inline">\theta \ge 0</span>).</p>
</section>
<section id="multiplicity-adjustment-via-prior-odds" class="level2">
<h2 data-anchor-id="multiplicity-adjustment-via-prior-odds">Multiplicity adjustment via prior odds</h2>
<p>For each test <span class="math inline">i = 1, \dots, m</span>, let <span class="math inline">H_{1,i}</span> denote the directional claim corresponding to the posterior-dominant sign, used to compute <span class="math inline">pd_i = \Pr(H_{1,i} \mid y)</span>, with complement <span class="math inline">\Pr(H_{0,i} \mid y) = 1 - pd_i</span>. If the <span class="math inline">m</span> tests are exchangeable and <span class="math inline">\pi_0 = \Pr(H_{0,i})</span> denotes the prior probability that the data-disfavored hypothesis holds for a given test, then <span class="math inline">\pi_0</span> is the expected proportion of tests for which no genuine effect exists in the favored direction; accordingly, the expected number of such tests is <span class="math inline">m\pi_0</span>.</p>
<p>If the tests are independent, the probability of the global null <span class="math inline">H_0</span>, the event that no tested effect lies in its data-favored direction, is: <span class="math display">
\Pr(H_0) = \pi_0^m, \qquad \text{equivalently} \qquad \pi_0 = \Pr(H_0)^{1/m}.
</span> In this scenario, setting <span class="math inline">\pi_0 = \Pr(H_{1,i}) = \Pr(H_{0,i}) = 0.5</span> (the symmetric prior introduced in the previous section) assigns near-certainty to the event that at least one effect lies in its claimed direction, since <span class="math inline">\Pr(H_0) = 0.5^m</span> tends to <span class="math inline">0</span> as <span class="math inline">m</span> grows. A principled response is to redistribute prior probability toward the data-disfavored hypothesis for each claim as a function of family size <span class="math inline">m</span> <span class="citation" data-cites="Jeffreys1938 Westfall1997">(<a href="#ref-Jeffreys1938" role="doc-biblioref">Jeffreys, 1938</a>; <a href="#ref-Westfall1997" role="doc-biblioref">Westfall et al., 1997</a>)</span>. This adjustment enters through <span class="math inline">\pi_0</span>, which modifies the prior odds. For each test, the adjusted posterior odds are: <span class="math display">
\frac{pd_{\mathrm{adj},i}}{1 - pd_{\mathrm{adj},i}} = \frac{pd_i}{1-pd_i} \times \frac{1 - \pi_0}{\pi_0},
</span> and solving for the adjusted posterior probability gives: <span class="math display">
pd_{\mathrm{adj},i} = \frac{pd_i\,(1 - \pi_0)}{pd_i\,(1 - \pi_0) + (1 - pd_i)\,\pi_0}.
</span> Because the prior is symmetric and <span class="math inline">pd_i</span> is always the posterior probability of the dominant direction, the factor <span class="math inline">(1-\pi_0)/\pi_0</span> acts as a single scalar penalty applied identically regardless of the effect’s sign.</p>
<p>We emphasize that <span class="math inline">H_{0,i}</span> is a <em>directional</em> null, the disfavored region <span class="math inline">\theta_i \le \theta_{\text{null}}</span> (taking the favored side as positive) covers both a truly (point) null effect and an effect of the opposite sign that the data have mis-signed. Additionally, <span class="math inline">\pi_0</span> is a <em>family-level</em> prior, distinct from the continuous within-model prior on each <span class="math inline">\theta_i</span>, under which the point <span class="math inline">\theta_i = \theta_{\text{null}}</span> has zero mass; the procedure accordingly does not quantify evidence for the point null at any individual test, it only adjusts the weight given to directional claims in light of the expected proportion of genuine discoveries in the family.</p>
<p>Researchers encode their expectations through <span class="math inline">\pi_0</span> or, equivalently under independence, through the global-null prior <span class="math inline">\Pr(H_0) = \pi_0^m</span>: lower values are appropriate for well-established effects with substantial prior information, higher values for settings with greater uncertainty, as in exploratory research. For fixed <span class="math inline">\Pr(H_0)</span>, larger families imply higher <span class="math inline">\pi_0</span>, then the correction acts nonlinearly on the posterior evidence, leaving larger <span class="math inline">pd_i</span> values comparatively less affected (<a href="#fig-prior-adj" class="quarto-xref" aria-expanded="false">Figure&nbsp;3</a>).</p>
<p>A boundary condition arises when the specified <span class="math inline">\pi_0</span> falls below <span class="math inline">0.5</span> (which, for a fixed global null, occurs when <span class="math inline">m</span> is small and <span class="math inline">\Pr(H_0)</span> is very low), inflating the posterior odds in favor of <span class="math inline">H_1</span> rather than penalizing them. We therefore cap <span class="math inline">\pi_0</span> at <span class="math inline">0.5</span>, ensuring the adjustment acts exclusively as a conservative safeguard; when no penalty is warranted, <span class="math inline">pd_{\mathrm{adj},i} = pd_i</span>. Furthermore, since <span class="math inline">pd \in [0.5, 1]</span>, the adjusted probability of direction is also bounded below by <span class="math inline">0.5</span>.</p>
</section>
<section id="error-rates-under-the-prior-odds-adjustment" class="level2">
<h2 data-anchor-id="error-rates-under-the-prior-odds-adjustment">Error rates under the prior-odds adjustment</h2>
<p>For a family of <span class="math inline">m</span> such tests, let <span class="math inline">R</span> denote the total number of rejections and <span class="math inline">V</span> the number of false rejections (rejected true nulls). The target error rate is the False Discovery Rate (FDR), <span class="math display">
\mathrm{FDR} = \mathbb{E}\!\left[\frac{V}{\max(R, 1)}\right],
</span> where the <span class="math inline">\max(R, 1)</span> sets the ratio to zero when no hypothesis is rejected <span class="citation" data-cites="Benjamini1995">(<a href="#ref-Benjamini1995" role="doc-biblioref">Benjamini &amp; Hochberg, 1995</a>)</span>. The FDR factorizes as the product of the positive False Discovery Rate <span class="citation" data-cites="Storey2003">(pFDR, <a href="#ref-Storey2003" role="doc-biblioref">Storey, 2003</a>)</span> and the probability of at least one rejection, <span class="math inline">\mathrm{FDR} = \mathrm{pFDR} \times \Pr(R &gt; 0)</span>. For a single test with prior null probability <span class="math inline">\pi_0</span>, <span class="math display">
\mathrm{pFDR} = \frac{\pi_0\,\alpha}{\pi_0\,\alpha + (1 - \pi_0)(1 - \beta)},
</span> where <span class="math inline">\alpha</span> is the per-test Type I error rate and <span class="math inline">1 - \beta</span> the power <span class="citation" data-cites="Storey2003 berger2023">(<a href="#ref-berger2023" role="doc-biblioref">Berger, 2023</a>; <a href="#ref-Storey2003" role="doc-biblioref">Storey, 2003</a>)</span>. The proposed correction fixes <span class="math inline">\pi_0</span> at the researcher’s prior and, as we now show, implicitly reduces <span class="math inline">\alpha</span> by tightening the decision threshold. Writing the adjusted rule <span class="math inline">pd_{\mathrm{adj},i} &gt; c</span> in odds form and substituting the adjusted odds, <span class="math display">
\frac{pd_{\mathrm{adj},i}}{1 - pd_{\mathrm{adj},i}} = \frac{pd_i}{1 - pd_i} \times \frac{1 - \pi_0}{\pi_0},
</span> the rule becomes a condition on the unadjusted odds, <span class="math display">
\frac{pd_i}{1 - pd_i} &gt; \frac{c}{1 - c} \times \frac{\pi_0}{1 - \pi_0},
</span> or, on the probability scale, a stricter threshold on the raw <span class="math inline">pd_i</span>: <span class="math display">
pd_i &gt; c^*, \qquad c^* = \frac{c\,\pi_0}{(1 - c)(1 - \pi_0) + c\,\pi_0},
</span> with <span class="math inline">c^* &gt; c</span> whenever <span class="math inline">\pi_0 &gt; 0.5</span>. Since <span class="math inline">c^*</span> is increasing in <span class="math inline">\pi_0</span>, the decision threshold is tied directly to the prior probability of the null. The more plausible the null is held to be a priori, the stronger the posterior evidence required to claim a directional effect <span class="citation" data-cites="Benjamin2017">(<a href="#ref-Benjamin2017" role="doc-biblioref">Benjamin et al., 2017</a>)</span>. When the null distribution of <span class="math inline">pd</span> is uniform on <span class="math inline">[0.5, 1]</span>, the per-test probability of rejecting a true null is <span class="math inline">\alpha^* = 2(1 - c^*)</span>; under an informative skeptical prior, which shrinks the posterior toward the null, this rate is even smaller. Since <span class="math inline">\alpha^* &lt; \alpha</span>, the adjustment lowers both factors of the decomposition, the pFDR, in which <span class="math inline">\alpha</span> enters directly, and <span class="math inline">\Pr(R &gt; 0)</span>, which falls as the test becomes more conservative, and therefore reduces the FDR relative to the unadjusted rule.</p>
<section id="simulation-study" class="level3">
<h3 data-anchor-id="simulation-study">Simulation Study</h3>
<p>We conducted a fully crossed simulation study, with 10,000 replications per cell, to examine the adjustment under both correctly specified and misspecified priors (<span class="math inline">\pi_0</span>). We varied the per-test null prior supplied to the procedure, <span class="math inline">\pi_0 \in \{0.50, 0.6, \dots, 0.9\}</span>; the true probability that each hypothesis is null, <span class="math inline">\pi_{0\text{true}} \in \{0.5, 0.6, \dots, 1.0\}</span>; the family size <span class="math inline">m \in \{4, 8, 10, 20\}</span>; and the sample size <span class="math inline">n \in \{30, 50, 100\}</span>. At each replication the number of true null effects (<span class="math inline">\theta_i = 0</span>) was drawn from <span class="math inline">\mathrm{Binomial}(m, \pi_{0\text{true}})</span> and the remaining effects set to <span class="math inline">\theta_i = 0.3</span>; observations were generated as <span class="math inline">y_i \sim \mathcal{N}(\theta_i, 1)</span>, and the posterior obtained from a conjugate normal–normal model with <span class="math inline">y_i \mid \theta \sim \mathcal{N}(\theta, 1)</span> and prior <span class="math inline">\theta \sim \mathcal{N}(0, 2)</span>. We declared support for a directional effect when <span class="math inline">pd &gt; 0.975</span> and evaluated the FDR, the FWER, and average power, the proportion of true effects detected <span class="citation" data-cites="Benjamini1995 Grant2025">(<a href="#ref-Benjamini1995" role="doc-biblioref">Benjamini &amp; Hochberg, 1995</a>; <a href="#ref-Grant2025" role="doc-biblioref">Izmirlian et al., 2025</a>)</span>. The diagonal <span class="math inline">\pi_0 = \pi_{0\text{true}}</span> corresponds to a correctly specified prior.</p>
<p><a href="#fig-ind-fdr-pw" class="quarto-xref" aria-expanded="false">Figure&nbsp;4</a> shows the FDR resulting from our procedure across the grid. The column <span class="math inline">\pi_0 = 0.5</span> is the unadjusted rule: there the prior odds are one, no correction is applied (<span class="math inline">pd_{\mathrm{adj}} = pd</span>), and the FDR inflates with the family size <span class="math inline">m</span> and the true null proportion <span class="math inline">\pi_{0\text{true}}</span>, reaching <span class="math inline">0.64</span> when the family is large and most effects are null. Increasing <span class="math inline">\pi_0</span> brings the FDR under control: it is held low whenever the specified <span class="math inline">\pi_0</span> is at least the true proportion, and inflates only under substantial underestimation, when a small <span class="math inline">\pi_0</span> is paired with a large <span class="math inline">\pi_{0\text{true}}</span> at large <span class="math inline">m</span>. This control trades off power, which decreases as <span class="math inline">\pi_0</span> increases; because average power does not vary with <span class="math inline">m</span> (for fixed <span class="math inline">\pi_{0\text{true}}</span> and <span class="math inline">\pi_0</span>), we display <span class="math inline">m = 20</span> as a representative condition (<a href="#fig-ind-fdr-pw" class="quarto-xref" aria-expanded="false">Figure&nbsp;4</a>).</p>
<p><a href="#fig-ind-fwer" class="quarto-xref" aria-expanded="false">Figure&nbsp;5</a> shows the FWER of the same rule (for <span class="math inline">n = 50</span>, as a representative case). Unlike the FDR, the FWER is not held low by the per-test adjustment: it grows with the family size <span class="math inline">m</span>, reaching <span class="math inline">0.64</span> for the unadjusted rule with a large family of mostly null effects. Increasing <span class="math inline">\pi_0</span> lowers it substantially, at <span class="math inline">\pi_0 = 0.9</span> it stays at or below about <span class="math inline">0.10</span>.</p>
</section>
<section id="comparison-with-other-bayesian-methods" class="level3">
<h3 data-anchor-id="comparison-with-other-bayesian-methods">Comparison with other Bayesian methods</h3>
<p>We compare the proposed method with two Bayesian alternatives that differ both in the form of the claim they license and in the error they aim to control. The first, hereafter the <em>joint directional rule</em>, orders the directional claims by their posterior probability and accepts the largest set whose joint posterior probability is at least <span class="math inline">1-\alpha</span> <span class="citation" data-cites="Gelman2000 Pruzek2016">(<a href="#ref-Gelman2000" role="doc-biblioref">Gelman &amp; Tuerlinckx, 2000</a>; <a href="#ref-Pruzek2016" role="doc-biblioref">Pruzek, 2016</a>)</span>. Its output is a single one-sided statement about signs, that is “all accepted effects lie in their claimed direction”, and the quantity it bounds is the familywise probability of a sign (Type S) error. The second, hereafter the <em>simultaneous-band rule</em>, computes credible intervals with <span class="math inline">1-\alpha</span> joint coverage, meaning that with probability <span class="math inline">1-\alpha</span> every interval contains its parameter, and declares an effect whenever an interval excludes the null value <span class="citation" data-cites="Schnell2020 Schnell2016 Box1992">(<a href="#ref-Box1992" role="doc-biblioref">Box &amp; Tiao, 1992</a>; <a href="#ref-Schnell2016" role="doc-biblioref">Schnell et al., 2016</a>; <a href="#ref-Schnell2020" role="doc-biblioref">Schnell et al., 2020</a>)</span>. Since an interval that covers a truly null parameter cannot exclude it, the probability of any false declaration is at most <span class="math inline">\alpha</span>. Both procedures act on the posterior alone, whereas the proposed method combines the posterior with the prior odds, adjusted for the family of hypotheses under test.</p>
<p>To benchmark the three procedures, we replicate the simulation described above, holding <span class="math inline">n = 50</span> and <span class="math inline">\pi_{0\text{true}} = 0.7</span> fixed while varying the family size <span class="math inline">m</span>. The prior-odds adjustment is evaluated at <span class="math inline">\pi_0 = \pi_{0\text{true}}</span>, its best-case calibration. All procedures use <span class="math inline">\alpha = 0.05</span>: the prior-odds rule claims a directional effect when the adjusted <span class="math inline">pd</span> exceeds <span class="math inline">c = 1 - \alpha/2 = 0.975</span>, the joint directional rule accepts directional claims as long as their joint posterior probability remains at least <span class="math inline">1 - \alpha = 0.95</span>, and the simultaneous-band rule declares an effect when the <span class="math inline">95\%</span> joint-coverage band excludes zero. <a href="#fig-compare" class="quarto-xref" aria-expanded="false">Figure&nbsp;6</a> reports the resulting FDR, FWER, and power for each procedure across values of <span class="math inline">m</span>.</p>
<p>In this setting, the simultaneous-band rule is the most stringent: it keeps the FWER, and hence the FDR, below the nominal level at every <span class="math inline">m</span>, since only a proportion <span class="math inline">\pi_{0\text{true}} = 0.7</span> of the effects are truly null. The joint directional rule is the most liberal, with the FDR reaching <span class="math inline">0.22</span> and the FWER rising to <span class="math inline">0.57</span> at the largest family size.</p>
<p>The error criteria trade off power (rightmost panel of <a href="#fig-compare" class="quarto-xref" aria-expanded="false">Figure&nbsp;6</a>): the joint directional rule detects the most true effects (around <span class="math inline">0.62</span>), the prior-odds rule maintains nearly constant power across <span class="math inline">m</span> (around <span class="math inline">0.43</span>), and the simultaneous-band rule loses power as the family grows (from <span class="math inline">0.36</span> at <span class="math inline">m = 4</span> to <span class="math inline">0.18</span> at <span class="math inline">m = 20</span>). Choosing among the procedures is therefore a deliberate trade between power and the error one most wants to limit.</p>
</section>
</section>
</section>
<section id="application-worked-example-with-the-r-package-multibayes" class="level1">
<h1>Application: worked example with the R Package <code>multibayes</code></h1>
<p>The procedure is implemented in the <code>multibayes</code> R package, which provides functions for computing adjusted <span class="math inline">pd</span> values from either raw posterior draws or a vector of unadjusted <span class="math inline">pd</span> values. The core function, <code>pd.adjust()</code>, accepts posterior draws directly and computes <span class="math inline">pd</span> values internally when needed. The prior is supplied in either of two ways: directly as the per-test null prior <span class="math inline">\pi_0</span>, or as the global-null prior <span class="math inline">\Pr(H_0)</span>, from which <span class="math inline">\pi_0 = \Pr(H_0)^{1/m}</span> is recovered under independence. The output includes the adjusted <span class="math inline">pd</span> values, the tested null value, the per-test null probability <span class="math inline">\pi_0</span>, and the number of tests <span class="math inline">m</span>. Unadjusted <span class="math inline">pd</span> values are retained alongside adjusted ones to facilitate direct comparison; when posterior draws are provided as input, the posterior median for each parameter is also returned. <code>pd.adjust()</code> returns the per-test correction, and <code>order = TRUE</code> sorts the hypotheses by strength of evidence. The decision threshold may be given either as a <span class="math inline">pd</span> cutoff <span class="math inline">c</span> (argument <code>threshold</code>, default <span class="math inline">0.975</span>) or, equivalently, as a nominal per-test rate (argument <code>alpha</code>, with <span class="math inline">c = 1 - \alpha/2</span>); in either case the function reports the implied adjusted cutoff <span class="math inline">c^*</span> on the raw <span class="math inline">pd</span>, which summarizes what the chosen <span class="math inline">\pi_0</span> implies.</p>
<p>For this example, we use the openly available dataset from <span class="citation" data-cites="Lin2020">Lin et al. (<a href="#ref-Lin2020" role="doc-biblioref">2020</a>)</span>, who investigated the effect of ego depletion on conflict resolution across four studies. In their paradigm, an initial high-demand (vs.&nbsp;low-demand) task was followed by a Stroop task. For simplicity, we focus on Study 1, which tested the effects of congruency and ego depletion (within subjects). The dataset is readily accessible via the <code>afex</code> package <span class="citation" data-cites="Singmann2016">(<a href="#ref-Singmann2016" role="doc-biblioref">Singmann et al., 2016</a>)</span> and was chosen for this reason; this example is not intended as a critique of the original work. This dataset includes data from 253 participants; for this example, we randomly selected 80 participants.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages('remotes')</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>remotes<span class="sc">::</span><span class="fu">install_github</span>(<span class="st">"mar-cald/multibayes"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(multibayes)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(brms)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>data_stroop <span class="ot">&lt;-</span> <span class="fu">subset</span>(afex<span class="sc">::</span>stroop, <span class="at">subset =</span> study <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> pno <span class="sc">%in%</span> <span class="fu">sample</span>(<span class="fu">levels</span>(pno),</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> <span class="dv">80</span>)) <span class="sc">|&gt;</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    <span class="co"># remove useless levels id</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">id =</span> <span class="fu">droplevels</span>(pno)) <span class="sc">|&gt;</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>    <span class="co"># select relevant variables</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>dplyr<span class="sc">::</span><span class="fu">select</span>(id, condition, congruency, trialnum, acc, rt) <span class="sc">|&gt;</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>    <span class="co"># previous cong</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="fu">group_by</span>(id, condition) <span class="sc">|&gt;</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">prev_cong =</span> <span class="fu">lag</span>(congruency), <span class="at">trial =</span> <span class="fu">scale</span>(trialnum)[, <span class="dv">1</span>]) <span class="sc">|&gt;</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ungroup</span>() <span class="sc">|&gt;</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>    <span class="fu">na.omit</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Given the repeated-measures structure of the data and the large number of trials per participant, we fit a multilevel generalized linear model using <code>brms</code> <span class="citation" data-cites="Paul2017">(<a href="#ref-Paul2017" role="doc-biblioref">Bürkner, 2017</a>)</span> on reaction time (RT) data. A Lognormal model was specified, with default flat priors; these were adopted not as a principled recommendation, but to illustrate the method’s behavior under the most common applied scenario, which also represents the condition where the prior-odds adjustment is most suggested.</p>
<p>The model includes the effect of congruency (congruent vs.&nbsp;incongruent), previous congruency (congruent vs.&nbsp;incongruent), condition (depletion vs.&nbsp;control), and trial number (scaled within participant and condition). The sequential congruency effect was modeled as the interaction between congruency and previous congruency; the hypothesis that depletion amplifies the congruency effect over time was captured by the three-way congruency <span class="math inline">\times</span> condition <span class="math inline">\times</span> trial interaction. This yielded nine hypotheses (Table 1).</p>
<p>Although the theoretical hypotheses are directional (e.g., incongruent trials are expected to slow responses), <span class="math inline">pd</span> is computed uniformly as <span class="math inline">\max\!\big(\Pr(\hat{\theta} &gt; \theta_\text{null}),\, \Pr(\hat{\theta} &lt; \theta_\text{null})\big)</span> for all hypotheses.</p>
<table class="caption-top table">
<caption>Tested hypotheses for RT, evaluated on the log scale of the posterior.</caption>
<thead>
<tr class="header">
<th><strong>Hypothesis</strong></th>
<th style="text-align: center;"><strong><span class="math inline">\theta_\text{null}</span></strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">H_1</span>: congruency effect</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td><span class="math inline">H_2</span>: previous congruency effect</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="odd">
<td><span class="math inline">H_3</span>: condition effect</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td><span class="math inline">H_4</span>: trial number effect</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="odd">
<td><span class="math inline">H_5</span>: congruency <span class="math inline">\times</span> previous congruency interaction</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td><span class="math inline">H_6</span>: congruency <span class="math inline">\times</span> condition interaction</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="odd">
<td><span class="math inline">H_7</span>: congruency <span class="math inline">\times</span> trial interaction</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td><span class="math inline">H_8</span>: trial <span class="math inline">\times</span> condition interaction</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="odd">
<td><span class="math inline">H_9</span>: congruency <span class="math inline">\times</span> condition <span class="math inline">\times</span> trial interaction</td>
<td style="text-align: center;">0</td>
</tr>
</tbody>
</table>
<p>We retained only correct trials preceded by a correct trial (i.e., error and post-error trials were excluded), yielding <span class="math inline">5,965</span> observations.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>data_rt <span class="ot">&lt;-</span> data_stroop <span class="sc">|&gt;</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(id) <span class="sc">|&gt;</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(acc <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> <span class="fu">lag</span>(acc) <span class="sc">==</span> <span class="dv">1</span>) <span class="sc">|&gt;</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ungroup</span>()</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="co"># set contrast</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(data_rt<span class="sc">$</span>congruency) <span class="ot">&lt;-</span> <span class="fu">contr.sum</span>(<span class="dv">2</span>)<span class="sc">/</span><span class="dv">2</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(data_rt<span class="sc">$</span>prev_cong) <span class="ot">&lt;-</span> <span class="fu">contr.sum</span>(<span class="dv">2</span>)<span class="sc">/</span><span class="dv">2</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(data_rt<span class="sc">$</span>condition) <span class="ot">&lt;-</span> <span class="fu">contr.sum</span>(<span class="dv">2</span>)<span class="sc">/</span><span class="dv">2</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>mod_rt <span class="ot">&lt;-</span> <span class="fu">brm</span>(<span class="at">formula =</span> rt <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> congruency <span class="sc">*</span> prev_cong <span class="sc">+</span> congruency <span class="sc">*</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>    trial <span class="sc">*</span> condition <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> congruency <span class="sc">+</span> prev_cong <span class="sc">+</span> trial <span class="sc">+</span> condition <span class="sc">||</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>    id), <span class="at">family =</span> <span class="fu">lognormal</span>(), <span class="at">data =</span> data_rt, <span class="at">cores =</span> <span class="dv">3</span>, <span class="at">chains =</span> <span class="dv">3</span>, <span class="at">iter =</span> <span class="dv">8000</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Since <code>pd.adjust()</code> computes <span class="math inline">pd</span> values automatically from a matrix of posterior draws, we extracted the relevant draws from the model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>draws_rt <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(mod_rt)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>par_names <span class="ot">&lt;-</span> <span class="fu">colnames</span>(draws_rt)[<span class="dv">2</span><span class="sc">:</span><span class="dv">10</span>]</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>draws_rt <span class="ot">&lt;-</span> draws_rt[, par_names]</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">pd.adjust</span>(<span class="at">draws =</span> draws_rt, <span class="at">pi0 =</span> <span class="fl">0.7</span>, <span class="at">null.value =</span> <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Prior-odds adjusted probability of direction
Tests: 9  |  pi0 = 0.7
Decision: raw pd &gt; 0.9891 (adjusted from 0.975); effective per-test
alpha 0.0217 (from 0.05)

                               median.est null.value     pd pd.adj
b_congruency1                     -0.1439          0 1.0000 1.0000
b_prev_cong1                      -0.0166          0 0.9803 0.9553
b_trial                            0.0119          0 0.9369 0.8642
b_condition1                       0.0063          0 0.6509 0.5000
b_congruency1:prev_cong1           0.0223          0 0.9583 0.9079
b_congruency1:trial               -0.0033          0 0.7206 0.5250
b_congruency1:condition1          -0.0166          0 0.9291 0.8488
b_trial:condition1                 0.0071          0 0.8936 0.7825
b_congruency1:trial:condition1    -0.0028          0 0.5961 0.5000
                               direction
b_congruency1                  two.sided
b_prev_cong1                   two.sided
b_trial                        two.sided
b_condition1                   two.sided
b_congruency1:prev_cong1       two.sided
b_congruency1:trial            two.sided
b_congruency1:condition1       two.sided
b_trial:condition1             two.sided
b_congruency1:trial:condition1 two.sided</code></pre>
</div>
</div>
<p>The function was called with a per-test null prior of <span class="math inline">\pi_0 = 0.7</span> (shown in the printed header), encoding the skeptical expectation that roughly 70% of the tested effects are null. The header also reports the equivalent decision this implies: at the default cutoff <span class="math inline">c = 0.975</span>, a raw <span class="math inline">pd</span> must now exceed the stricter adjusted threshold <span class="math inline">c^* = 0.989</span>.</p>
<p>The adjustment’s effect varies with the strength of the underlying evidence. The predictor <code>b_congruency1</code> carries <span class="math inline">pd = 1</span> and is left untouched (<span class="math inline">pd_\text{adj} = 1</span>). Terms with lower but still substantial evidence are pulled down only mildly: <code>b_prev_cong1</code> (<span class="math inline">0.980 \to 0.955</span>), <code>b_trial</code> (<span class="math inline">0.937 \to 0.864</span>), <code>b_congruency1:prev_cong1</code> (<span class="math inline">0.958 \to 0.908</span>), <code>b_congruency1:condition1</code> (<span class="math inline">0.929 \to 0.849</span>), and <code>b_trial:condition1</code> (<span class="math inline">0.894 \to 0.783</span>). In contrast, parameters with weak evidence are shrunk substantially toward <span class="math inline">0.5</span>: <code>b_condition1</code> (<span class="math inline">0.651 \to 0.500</span>), <code>b_congruency1:trial</code> (<span class="math inline">0.721 \to 0.525</span>), and the three-way interaction <code>b_congruency1:trial:condition1</code> (<span class="math inline">0.596 \to 0.500</span>).</p>
<p>A companion function, <code>joint()</code>, computes by default the joint posterior probability of the <span class="math inline">k</span> strongest directional claims, for each <span class="math inline">k</span>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">joint</span>(draws_rt, <span class="at">null.value =</span> <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                               median.est null.value     pd direction
b_congruency1                     -0.1439          0 1.0000 two.sided
b_prev_cong1                      -0.0166          0 0.9803 two.sided
b_congruency1:prev_cong1           0.0223          0 0.9583 two.sided
b_trial                            0.0119          0 0.9369 two.sided
b_congruency1:condition1          -0.0166          0 0.9291 two.sided
b_trial:condition1                 0.0071          0 0.8936 two.sided
b_congruency1:trial               -0.0033          0 0.7206 two.sided
b_condition1                       0.0063          0 0.6509 two.sided
b_congruency1:trial:condition1    -0.0028          0 0.5961 two.sided
                               joint_cum
b_congruency1                     1.0000
b_prev_cong1                      0.9803
b_congruency1:prev_cong1          0.9412
b_trial                           0.8812
b_congruency1:condition1          0.8191
b_trial:condition1                0.7340
b_congruency1:trial               0.5366
b_condition1                      0.3532
b_congruency1:trial:condition1    0.2232</code></pre>
</div>
</div>
<p>The rows are sorted by decreasing <span class="math inline">pd</span>, and the <code>joint_cum</code> column reports the posterior probability that the top <span class="math inline">k</span> claims hold simultaneously; a high value supports accepting that set of claims as a whole. Here the two strongest claims hold jointly with probability <span class="math inline">0.98</span> and the three strongest with <span class="math inline">0.94</span>; the joint probability then declines as weaker claims are added, indicating how many of the leading effects can be reported as a jointly supported set.</p>
<p>Setting <code>interval = TRUE</code> returns simultaneous equi-tailed credible intervals instead:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">joint</span>(draws_rt, <span class="at">interval =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                      lower          est        upper
b_congruency1                  -0.191547431 -0.143902841 -0.097013276
b_prev_cong1                   -0.040931203 -0.016649556  0.006550712
b_trial                        -0.010103453  0.011930699  0.034360234
b_condition1                   -0.041911018  0.006263499  0.055382483
b_congruency1:prev_cong1       -0.012481840  0.022342004  0.056749925
b_congruency1:trial            -0.019082492 -0.003316115  0.012417422
b_congruency1:condition1       -0.048854131 -0.016551526  0.015382114
b_trial:condition1             -0.008945797  0.007125574  0.023144055
b_congruency1:trial:condition1 -0.034805697 -0.002829134  0.028034847
                               prob
b_congruency1                  0.95
b_prev_cong1                   0.95
b_trial                        0.95
b_condition1                   0.95
b_congruency1:prev_cong1       0.95
b_congruency1:trial            0.95
b_congruency1:condition1       0.95
b_trial:condition1             0.95
b_congruency1:trial:condition1 0.95</code></pre>
</div>
</div>
<p>Under this stricter criterion, only <code>b_congruency1</code> excludes zero (simultaneous band <span class="math inline">[-0.19, -0.10]</span>).</p>
</section>
<section id="discussion" class="level1">
<h1>Discussion</h1>
<p>The probability of direction (<span class="math inline">pd</span>) is the posterior mass on the data-favored side of a reference null value, equivalently, the larger of the two one-sided posterior probabilities. Under within-model prior symmetry each such data-selected hypothesis is evaluated under prior odds of one, so that the procedure attributes equal a priori plausibility to the direction selected after inspection of the data. In this scenario, if multiple hypothesis are tested, the procedure becomes a priori almost certain that at least one favored direction is genuine. The approach developed here addresses this by recasting multiplicity as a problem of prior specification: building on the foundational work of <span class="citation" data-cites="Jeffreys1938 Westfall1997">Jeffreys (<a href="#ref-Jeffreys1938" role="doc-biblioref">1938</a>; see also <a href="#ref-Westfall1997" role="doc-biblioref">Westfall et al., 1997</a>)</span> and Bayesian approaches to FDR control <span class="citation" data-cites="Scott2006 Scott2010 Guo2010 Abraham2022 Efron2001 Storey2003 Storey2002 Stephens2017">(<a href="#ref-Abraham2022" role="doc-biblioref">Abraham et al., 2022</a>; <a href="#ref-Efron2001" role="doc-biblioref">Efron et al., 2001</a>; <a href="#ref-Guo2010" role="doc-biblioref">Guo &amp; Heitjan, 2010</a>; <a href="#ref-Scott2006" role="doc-biblioref">Scott &amp; Berger, 2006</a>; <a href="#ref-Scott2010" role="doc-biblioref">Scott &amp; Berger, 2010</a>; <a href="#ref-Stephens2017" role="doc-biblioref">Stephens, 2017</a>; <a href="#ref-Storey2002" role="doc-biblioref">Storey, 2002</a>, <a href="#ref-Storey2003" role="doc-biblioref">2003</a>)</span>, the correction requires researchers to specify the prior proportion of effects expected to be null. Making this prior explicit serves two purposes. For researchers using diffuse within-model priors, it provides a principled way to encode skepticism at the family level without committing to informative priors on individual parameters. For researchers who judge the implicit prior appropriate and decline the adjustment, it nonetheless renders that commitment transparent.</p>
<p>Related corrections have been implemented for specific testing contexts, such as post-hoc tests in JASP <span class="citation" data-cites="Bergh2020 deJong2019">(<a href="#ref-deJong2019" role="doc-biblioref">Jong, 2019</a>; <a href="#ref-Bergh2020" role="doc-biblioref">van den Bergh et al., 2020</a>)</span>. The present procedure extends this logic to <span class="math inline">pd</span> and provides a general-purpose implementation for applied use, applicable to directly to posterior draws or any posterior-derived <span class="math inline">pd</span>, including cases where <span class="math inline">pd</span> values arise from multiple separate analyses within the same manuscript <span class="citation" data-cites="Ciranka2026 Philippe2021">(<a href="#ref-Philippe2021" role="doc-biblioref">Blondé et al., 2021</a>; <a href="#ref-Ciranka2026" role="doc-biblioref">Ciranka et al., 2026</a>)</span>. This raises the question of how to define the hypothesis family to which the correction applies <span class="citation" data-cites="Shaffer1995 Hochberg1987">(<a href="#ref-Hochberg1987" role="doc-biblioref">Hochberg &amp; Tamhane, 1987</a>; <a href="#ref-Shaffer1995" role="doc-biblioref">Shaffer, 1995</a>)</span>. Although no universal consensus exists regarding what constitutes a family, we favor the criteria proposed by <span class="citation" data-cites="Westfall2011">Westfall et al. (<a href="#ref-Westfall2011" role="doc-biblioref">2011</a>)</span>, where a family is a set of questions that <em>“form a natural and coherent unit, [are] considered simultaneously in the decision-making process, and/or present a set over which one plays pick-the-winner”</em>. Regardless of the chosen definition, authors should clearly specify their chosen family and explain how it serves the study’s substantive goals.</p>
<p>We further recommend that researchers justify their choice of <span class="math inline">\pi_0</span>, the prior proportion of effects expected to be null, by drawing on theory, expert elicitation, or domain expertise <span class="citation" data-cites="Hagan2019">(<a href="#ref-Hagan2019" role="doc-biblioref">O’Hagan, 2019</a>)</span>. More generally, a high prior probability suits exploratory settings with many uncertain hypotheses, while a lower value is warranted in confirmatory settings. For applied reporting, the unadjusted <span class="math inline">pd</span> should accompany one multiplicity-adjusted measure, with the number of tests and <span class="math inline">\pi_0</span> clearly stated.</p>
<p>Although our approach derives from the Bayesian FDR literature, it differs from it in a fundamental respect. There, <span class="math inline">\pi_0</span> itself carries a prior distribution and is typically estimated from the data; here, it is specified by the user. The good frequentist properties of our procedure therefore hold only when the user-specified <span class="math inline">\pi_0</span> is approximately correct. A researcher may instead deliberately adopt a more skeptical prior, tightening control of Type I error at the cost of higher Type II error; the optimal value depends on the relative costs of the two.</p>
<p>Two limitations of the present framework warrant attention. First, the procedure assumes that all hypotheses are exchangeable. Exchangeability means each hypothesis receives the same prior penalty, even when some effects are regarded as more plausible a priori than others. Because the penalty shrinks weak evidence far more than strong evidence, genuine effects with strong support still survive; the price of a uniform proportion is therefore a modest loss of power on hypotheses one believes more likely to be true, rather than a loss of error control, which is preserved as long as the specified proportion is reasonable. Accommodating differential prior plausibility would require specifying and calibrating a separate <span class="math inline">\pi_0</span> for each test, with the realized error rate then governed by every individual value.</p>
<p>Second, it does not provide evidence for a point null hypothesis. The procedure evaluates directional claims defined by inequalities (e.g., <span class="math inline">\theta &gt; \theta_{\text{null}}</span> vs.&nbsp;<span class="math inline">\theta \leq \theta_{\text{null}}</span>), and while the complementary hypothesis includes the null value, that value receives no special status; non-rejection therefore reflects the absence of a directional discovery, not evidence in favor of <span class="math inline">\theta = \theta_{\text{null}}</span>. It bears noting, however, that the prior-odds correction itself is not new, it applies a classical multiplicity strategy <span class="citation" data-cites="Jeffreys1938 Westfall1997 deJong2019">(<a href="#ref-Jeffreys1938" role="doc-biblioref">Jeffreys, 1938</a>; <a href="#ref-deJong2019" role="doc-biblioref">Jong, 2019</a>; <a href="#ref-Westfall1997" role="doc-biblioref">Westfall et al., 1997</a>)</span> to the probability of direction, and, because it acts on the prior odds alone, it extends in principle to other Bayes factor approaches <span class="citation" data-cites="Heck2023 Morey2011 Ly2016 Dienes2016">(<a href="#ref-Dienes2016" role="doc-biblioref">Dienes, 2016</a>; <a href="#ref-Heck2023" role="doc-biblioref">Heck et al., 2023</a>; <a href="#ref-Ly2016" role="doc-biblioref">Ly et al., 2016</a>; <a href="#ref-Morey2011" role="doc-biblioref">Morey &amp; Rouder, 2011</a>)</span>. When joint modeling is feasible, an alternative is to integrate evidence across hypotheses through joint posterior probabilities <span class="citation" data-cites="Box1992 Gelman2000 Pruzek2016 Schnell2020">(<a href="#ref-Box1992" role="doc-biblioref">Box &amp; Tiao, 1992</a>; <a href="#ref-Gelman2000" role="doc-biblioref">Gelman &amp; Tuerlinckx, 2000</a>; <a href="#ref-Pruzek2016" role="doc-biblioref">Pruzek, 2016</a>; <a href="#ref-Schnell2020" role="doc-biblioref">Schnell et al., 2020</a>)</span>.</p>
<p>As Bayesian methods become increasingly common in psychological research, often in pragmatic workflows relying on default priors and fixed decision thresholds, the implications of multiplicity should be explicitly recognized. Additionally, although priors may be well-calibrated at the level of individual parameters, they do not by themselves account for multiplicity when many parameters are considered simultaneously. Ignoring this aspect leads fixed <span class="math inline">pd</span> thresholds to systematically overstate evidence for directional effects, especially as the number of tests grows. The adjustment proposed here addresses this gap by incorporating prior beliefs about the prevalence of null effects directly into <span class="math inline">pd</span>-based decisions. By doing so, it provides a principled and transparent way to account for multiplicity without altering the estimation model, yielding more reliable inferences in multi-parameter settings and reducing the risk that apparent effects reflect chance rather than substantive signals.</p>
<section id="author-contributions" class="level3">
<h3 data-anchor-id="author-contributions">Author Contributions</h3>
<p>Author roles were classified using the Contributor Roles Taxonomy (CRediT; <a href="https://credit.niso.org/" class="uri">https://credit.niso.org/</a>) as follows — Conceptualization: M. Calderan and G. Altoè; Methodology: M. Calderan, F. Gambarota, and L. Finos; Software: M. Calderan and F. Gambarota; Writing - Original Draft: M. Calderan; Writing - Review &amp; Editing: F. Gambarota, L. Finos, and G. Altoè; Visualization: M. Calderan; Supervision: L. Finos and G. Altoè. All authors approved the final version of the manuscript and agree to be accountable for the work.</p>
</section>
<section id="conflicts-of-interest" class="level3">
<h3 data-anchor-id="conflicts-of-interest">Conflicts of Interest</h3>
<p>The authors declare that there were no conflicts of interest with respect to the authorship or the publication of this article.</p>
</section>
<section id="acknowledgments" class="level3">
<h3 data-anchor-id="acknowledgments">Acknowledgments</h3>
<p>We are grateful to Jelle Goeman, Giovanni Parmigiani and Enrico Toffalini for insightful comments and discussion throughout the development of this work. We also thank Laura Sità and Matteo Manente for helpful feedback on earlier versions of the manuscript. The <code>multibayes</code> package code was reviewed and debugged with the assistance of AI tools.</p>
</section>
<section id="prior-versions" class="level3">
<h3 data-anchor-id="prior-versions">Prior Versions</h3>
<p>A version of this manuscript is posted as a preprint on PsyArXiv at <a href="https://osf.io/preprints/psyarxiv/8zwx2_v2" class="uri">https://osf.io/preprints/psyarxiv/8zwx2_v2</a>. The submitted manuscript shares its full content with that preprint.</p>
</section>
<section id="open-materials" class="level3">
<h3 data-anchor-id="open-materials">Open Materials</h3>
<p>Code is openly available in the <em>multibayes</em> repository on GitHub at <a href="https://github.com/mar-cald/multibayes" class="uri">https://github.com/mar-cald/multibayes</a>, and in the OSF repository at <a href="https://osf.io/q294m" class="uri">https://osf.io/q294m</a>.</p>
</section>
</section>
<section id="refs" class="level1">
<h1>References</h1>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-Abraham2022" class="csl-entry" role="listitem">
Abraham, K., Castillo, I., &amp; Roquain, É. (2022). Empirical bayes cumulative l-value multiple testing procedure for sparse sequences. <em>Electronic Journal of Statistics</em>, <em>16</em>(1), 2033–2081. <a href="https://doi.org/10.1214/22-EJS1979">https://doi.org/10.1214/22-EJS1979</a>
</div>
<div id="ref-Altoe2020" class="csl-entry" role="listitem">
Altoè, G., Bertoldo, G., Zandonella Callegher, C., Toffalini, E., Calcagnì, A., Finos, L., &amp; Pastore, M. (2020). Enhancing statistical inference in psychological research via prospective and retrospective design analysis. <em>Frontiers in Psychology</em>, <em>Volume 10 - 2019</em>. <a href="https://doi.org/10.3389/fpsyg.2019.02893">https://doi.org/10.3389/fpsyg.2019.02893</a>
</div>
<div id="ref-Ben2022" class="csl-entry" role="listitem">
Ben-Artzi, I., Luria, R., &amp; Shahar, N. (2022). Working memory capacity estimates moderate value learning for outcome-irrelevant features. <em>Scientific Reports</em>, <em>12</em>(1), 19677. <a href="https://doi.org/10.1038/s41598-022-21832-x">https://doi.org/10.1038/s41598-022-21832-x</a>
</div>
<div id="ref-Benjamin2017" class="csl-entry" role="listitem">
Benjamin, D. J., Berger, J. O., Johannesson, M., Nosek, B. A., Wagenmakers, E.-J., Berk, R., Bollen, K. A., Brembs, B., Brown, L., Camerer, C., Cesarini, D., Chambers, C. D., Clyde, M., Cook, T. D., De Boeck, P., Dienes, Z., Dreber, A., Easwaran, K., Efferson, C., … Johnson, V. E. (2017). Redefine statistical significance. <em>Nature Human Behaviour</em>, <em>2</em>(1), 6–10. <a href="https://doi.org/10.1038/s41562-017-0189-z">https://doi.org/10.1038/s41562-017-0189-z</a>
</div>
<div id="ref-Benjamini1995" class="csl-entry" role="listitem">
Benjamini, Y., &amp; Hochberg, Y. (1995). Controlling the <span>False Discovery Rate</span>: <span>A Practical</span> and <span>Powerful Approach</span> to <span>Multiple Testing</span>. <em>Journal of the Royal Statistical Society Series B: Statistical Methodology</em>, <em>57</em>(1), 289–300. <a href="https://doi.org/10.1111/j.2517-6161.1995.tb02031.x">https://doi.org/10.1111/j.2517-6161.1995.tb02031.x</a>
</div>
<div id="ref-berger2023" class="csl-entry" role="listitem">
Berger, J. O. (2023). Four types of frequentism and their interplay with bayesianism. <em>The New England Journal of Statistics in Data Science</em>, <em>1</em>, 126–137. <a href="https://doi.org/10.51387/22-NEJSDS4">https://doi.org/10.51387/22-NEJSDS4</a>
</div>
<div id="ref-Berry1999" class="csl-entry" role="listitem">
Berry, D. A., &amp; Hochberg, Y. (1999). Bayesian perspectives on multiple comparisons. <em>Journal of Statistical Planning and Inference</em>, <em>82</em>(1), 215–227. <a href="https://doi.org/10.1016/S0378-3758(99)00044-0">https://doi.org/10.1016/S0378-3758(99)00044-0</a>
</div>
<div id="ref-Philippe2021" class="csl-entry" role="listitem">
Blondé, P., Makowski, D., Sperduti, M., &amp; Piolino, P. (2021). In <span>Medio Stat Virtus</span>: Intermediate levels of mind wandering improve episodic memory encoding in a virtual environment. <em>Psychological Research</em>, <em>85</em>(4), 1613–1625. <a href="https://doi.org/10.1007/s00426-020-01358-5">https://doi.org/10.1007/s00426-020-01358-5</a>
</div>
<div id="ref-Box1992" class="csl-entry" role="listitem">
Box, G. E. P., &amp; Tiao, G. C. (1992). <em>Bayesian inference in statistical analysis</em> (1st ed.). Wiley. <a href="https://doi.org/10.1002/9781118033197">https://doi.org/10.1002/9781118033197</a>
</div>
<div id="ref-Bramley2022" class="csl-entry" role="listitem">
Bramley, N. R., &amp; Ruggeri, A. (2022). Children’s active physical learning is as effective and goal-targeted as adults’. <em>Developmental Psychology</em>, <em>58</em>(12), 2310–2321. <a href="https://doi.org/10.1037/dev0001435">https://doi.org/10.1037/dev0001435</a>
</div>
<div id="ref-Brissenden2023" class="csl-entry" role="listitem">
Brissenden, J. A., Adkins, T. J., Hsu, Y. T., &amp; Lee, T. G. (2023). Reward influences the allocation but not the availability of resources in visual working memory. <em>Journal of Experimental Psychology: General</em>, <em>152</em>(7), 1825–1839. <a href="https://doi.org/10.1037/xge0001370">https://doi.org/10.1037/xge0001370</a>
</div>
<div id="ref-Brissenden2024" class="csl-entry" role="listitem">
Brissenden, J. A., Scerbak, T., Albin, R. L., &amp; Lee, T. G. (2024). Motivational vigor in parkinson’s disease requires the short and long duration response to levodopa. <em>Movement Disorders</em>, <em>39</em>(1), 76–84. https://doi.org/<a href="https://doi.org/10.1002/mds.29659">https://doi.org/10.1002/mds.29659</a>
</div>
<div id="ref-Paul2017" class="csl-entry" role="listitem">
Bürkner, P.-C. (2017). <span class="nocase">brms</span>: An <span>R</span> package for <span>Bayesian</span> multilevel models using <span>Stan</span>. <em>Journal of Statistical Software</em>, <em>80</em>(1), 1–28. <a href="https://doi.org/10.18637/jss.v080.i01">https://doi.org/10.18637/jss.v080.i01</a>
</div>
<div id="ref-Calderan2026" class="csl-entry" role="listitem">
Calderan, M., &amp; Gambarota, F. (2026). <em>Multibayes: Bayesian multiplicity adjustments</em>. <a href="https://github.com/mar-cald/multibayes">https://github.com/mar-cald/multibayes</a>
</div>
<div id="ref-Casella1987" class="csl-entry" role="listitem">
Casella, G., &amp; Berger, R. L. (1987). Reconciling bayesian and frequentist evidence in the one-sided testing problem. <em>Journal of the American Statistical Association</em>, <em>82</em>(397), 106–111. <a href="https://doi.org/10.1080/01621459.1987.10478396">https://doi.org/10.1080/01621459.1987.10478396</a>
</div>
<div id="ref-Ciranka2026" class="csl-entry" role="listitem">
Ciranka, S., Chevallier, C., &amp; Nettle, D. (2026). Low socioeconomic status amplifies the perceived rarity of large rewards. <em>Cognition</em>, <em>270</em>, 106409. https://doi.org/<a href="https://doi.org/10.1016/j.cognition.2025.106409">https://doi.org/10.1016/j.cognition.2025.106409</a>
</div>
<div id="ref-Cohen1994" class="csl-entry" role="listitem">
Cohen, J. (1994). The earth is round (p <span><span class="math inline">&lt;</span></span> .05). <em>American Psychologist</em>, <em>49</em>(12), 997–1003. <a href="https://doi.org/10.1037/0003-066X.49.12.997">https://doi.org/10.1037/0003-066X.49.12.997</a>
</div>
<div id="ref-Dawid1994" class="csl-entry" role="listitem">
Dawid, A. P. (1994). Selection paradoxes of bayesian inference. <em>Lecture Notes-Monograph Series</em>, <em>24</em>, 211–220.
</div>
<div id="ref-Dienes2016" class="csl-entry" role="listitem">
Dienes, Z. (2016). How bayes factors change scientific practice. <em>Journal of Mathematical Psychology</em>, <em>72</em>, 78–89. <a href="https://doi.org/10.1016/j.jmp.2015.10.003">https://doi.org/10.1016/j.jmp.2015.10.003</a>
</div>
<div id="ref-Efron2001" class="csl-entry" role="listitem">
Efron, B., Tibshirani, R., Storey, J. D., &amp; Tusher, V. (2001). Empirical bayes analysis of a microarray experiment. <em>Journal of the American Statistical Association</em>, <em>96</em>(456), 1151–1160. <a href="https://doi.org/10.1198/016214501753382129">https://doi.org/10.1198/016214501753382129</a>
</div>
<div id="ref-Gelman2014" class="csl-entry" role="listitem">
Gelman, A., &amp; Carlin, J. (2014). Beyond power calculations: Assessing type s (sign) and type m (magnitude) errors. <em>Perspectives on Psychological Science</em>, <em>9</em>(6), 641–651. <a href="https://doi.org/10.1177/1745691614551642">https://doi.org/10.1177/1745691614551642</a>
</div>
<div id="ref-GelmanBook" class="csl-entry" role="listitem">
Gelman, A., Carlin, J. B., Stern, H. S., Dunson, D. B., Vehtari, A., &amp; Rubin, D. B. (2013). <em>Bayesian data analysis</em> (3rd ed.). Chapman; Hall/CRC. <a href="https://doi.org/10.1201/b16018">https://doi.org/10.1201/b16018</a>
</div>
<div id="ref-Gelman2012" class="csl-entry" role="listitem">
Gelman, A., Hill, J., &amp; Yajima, M. (2012). Why we (usually) don’t have to worry about multiple comparisons. <em>Journal of Research on Educational Effectiveness</em>, <em>5</em>(2), 189–211. <a href="https://doi.org/10.1080/19345747.2011.618213">https://doi.org/10.1080/19345747.2011.618213</a>
</div>
<div id="ref-Gelman2000" class="csl-entry" role="listitem">
Gelman, A., &amp; Tuerlinckx, F. (2000). Type s error rates for classical and bayesian single and multiple comparison procedures. <em>Computational Statistics</em>, <em>15</em>(3), 373–390. <a href="https://doi.org/10.1007/s001800000040">https://doi.org/10.1007/s001800000040</a>
</div>
<div id="ref-Gigerenzer2004" class="csl-entry" role="listitem">
Gigerenzer, G. (2004). Mindless statistics. <em>The Journal of Socio-Economics</em>, <em>33</em>(5), 587–606. <a href="https://doi.org/10.1016/j.socec.2004.09.033">https://doi.org/10.1016/j.socec.2004.09.033</a>
</div>
<div id="ref-Guo2010" class="csl-entry" role="listitem">
Guo, M., &amp; Heitjan, D. F. (2010). Multiplicity-calibrated bayesian hypothesis tests. <em>Biostatistics</em>, <em>11</em>(3), 473–483. <a href="https://doi.org/10.1093/biostatistics/kxq012">https://doi.org/10.1093/biostatistics/kxq012</a>
</div>
<div id="ref-Heck2023" class="csl-entry" role="listitem">
Heck, D. W., Boehm, U., Böing-Messing, F., Bürkner, P.-C., Derks, K., Dienes, Z., Fu, Q., Gu, X., Karimova, D., Kiers, H. A., et al. (2023). A review of applications of the bayes factor in psychological research. <em>Psychological Methods</em>, <em>28</em>(3), 558. <a href="https://doi.org/10.1037/met0000454">https://doi.org/10.1037/met0000454</a>
</div>
<div id="ref-Hochberg1987" class="csl-entry" role="listitem">
Hochberg, Y., &amp; Tamhane, A. C. (1987). <em>Multiple <span>Comparison Procedures</span></em> (1st ed.). Wiley. <a href="https://doi.org/10.1002/9780470316672">https://doi.org/10.1002/9780470316672</a>
</div>
<div id="ref-Hochman2025" class="csl-entry" role="listitem">
Hochman, S., Havedanloo, R., Heysieattalab, S., &amp; Soltanlou, M. (2025). How does language modulate the association between number and space? <span>A</span> registered report of a cross-cultural study of the spatial–numerical association of response codes effect. <em>Journal of Experimental Psychology: General</em>, <em>154</em>(2), 305–324. <a href="https://doi.org/10.1037/xge0001653">https://doi.org/10.1037/xge0001653</a>
</div>
<div id="ref-Hoijtink2016" class="csl-entry" role="listitem">
Hoijtink, H., Kooten, P. van, &amp; Hulsker, K. (2016). Why bayesian psychologists should change the way they use the bayes factor. <em>Multivariate Behavioral Research</em>, <em>51</em>(1), 2–10. <a href="https://doi.org/10.1080/00273171.2014.969364">https://doi.org/10.1080/00273171.2014.969364</a>
</div>
<div id="ref-Grant2025" class="csl-entry" role="listitem">
Izmirlian, G., Sirota, L. A., Berger, V. W., &amp; Kipnis, V. (2025). The fundamentals of multiplicity adjustment in biostatistics. <em>JNCI Monographs</em>, <em>2025</em>(68), 10–13. <a href="https://doi.org/10.1093/jncimonographs/lgae050">https://doi.org/10.1093/jncimonographs/lgae050</a>
</div>
<div id="ref-Jeffreys1938" class="csl-entry" role="listitem">
Jeffreys, H. (1938). Significance tests when several degrees of freedom arise simultaneously. <em>Proceedings of the Royal Society of London. Series A. Mathematical and Physical Sciences</em>, <em>165</em>(921), 161–198. <a href="https://doi.org/10.1098/rspa.1938.0052">https://doi.org/10.1098/rspa.1938.0052</a>
</div>
<div id="ref-Jevremov2024" class="csl-entry" role="listitem">
Jevremov, T., &amp; Pajić, D. (2024). Bayesian method in psychology: A bibliometric analysis. <em>Current Psychology</em>, <em>43</em>(10), 8644–8654. <a href="https://doi.org/10.1007/s12144-023-05003-3">https://doi.org/10.1007/s12144-023-05003-3</a>
</div>
<div id="ref-deJong2019" class="csl-entry" role="listitem">
Jong, T. de. (2019). <em>A bayesian approach to the correction for multiplicity</em>. PsyArXiv preprint. <a href="https://doi.org/10.31234/osf.io/s56mk">https://doi.org/10.31234/osf.io/s56mk</a>
</div>
<div id="ref-Kelter2023" class="csl-entry" role="listitem">
Kelter, R. (2023). How to choose between different bayesian posterior indices for hypothesis testing in practice. <em>Multivariate Behavioral Research</em>, <em>58</em>(1), 160–188. <a href="https://doi.org/10.1080/00273171.2021.1967716">https://doi.org/10.1080/00273171.2021.1967716</a>
</div>
<div id="ref-Kruschke2011" class="csl-entry" role="listitem">
Kruschke, J. K. (2011). Bayesian assessment of null values via parameter estimation and model comparison. <em>Perspectives on Psychological Science</em>, <em>6</em>(3), 299–312. <a href="https://doi.org/10.1177/1745691611406925">https://doi.org/10.1177/1745691611406925</a>
</div>
<div id="ref-Kruschke2018" class="csl-entry" role="listitem">
Kruschke, J. K. (2018). Rejecting or <span>Accepting Parameter Values</span> in <span>Bayesian Estimation</span>. <em>Advances in Methods and Practices in Psychological Science</em>, <em>1</em>(2), 270–280. <a href="https://doi.org/10.1177/2515245918771304">https://doi.org/10.1177/2515245918771304</a>
</div>
<div id="ref-Lakens2018" class="csl-entry" role="listitem">
Lakens, D., Scheel, A. M., &amp; Isager, P. M. (2018). Equivalence testing for psychological research: <span>A</span> tutorial. <em>Advances in Methods and Practices in Psychological Science</em>, <em>1</em>(2), 259–269. <a href="https://doi.org/10.1177/2515245918770963">https://doi.org/10.1177/2515245918770963</a>
</div>
<div id="ref-Lin2020" class="csl-entry" role="listitem">
Lin, H., Saunders, B., Friese, M., Evans, N. J., &amp; Inzlicht, M. (2020). Strong effort manipulations reduce response caution: A preregistered reinvention of the ego-depletion paradigm. <em>Psychological Science</em>, <em>31</em>(5), 531–547. <a href="https://doi.org/10.1177/0956797620904990">https://doi.org/10.1177/0956797620904990</a>
</div>
<div id="ref-Ly2016" class="csl-entry" role="listitem">
Ly, A., Verhagen, J., &amp; Wagenmakers, E.-J. (2016). Harold jeffreys’s default bayes factor hypothesis tests: Explanation, extension, and application in psychology. <em>Journal of Mathematical Psychology</em>, <em>72</em>, 19–32. <a href="https://doi.org/10.1016/j.jmp.2015.06.004">https://doi.org/10.1016/j.jmp.2015.06.004</a>
</div>
<div id="ref-Makowski2019" class="csl-entry" role="listitem">
Makowski, D., Ben-Shachar, M. S., Chen, S. H. A., &amp; Lüdecke, D. (2019). Indices of effect existence and significance in the bayesian framework. <em>Frontiers in Psychology</em>, <em>Volume 10 - 2019</em>. <a href="https://doi.org/10.3389/fpsyg.2019.02767">https://doi.org/10.3389/fpsyg.2019.02767</a>
</div>
<div id="ref-Makowski2020" class="csl-entry" role="listitem">
Makowski, D., Sperduti, M., Blondé, P., Nicolas, S., &amp; Piolino, P. (2020). The heart of cognitive control: Cardiac phase modulates processing speed and inhibition. <em>Psychophysiology</em>, <em>57</em>(3), e13490. <a href="https://doi.org/10.1111/psyp.13490">https://doi.org/10.1111/psyp.13490</a>
</div>
<div id="ref-Marsman2017" class="csl-entry" role="listitem">
Marsman, M., &amp; Wagenmakers, E.-J. (2017). Three insights from a bayesian interpretation of the one-sided p value. <em>Educational and Psychological Measurement</em>, <em>77</em>(3), 529–539. <a href="https://doi.org/10.1177/0013164416669201">https://doi.org/10.1177/0013164416669201</a>
</div>
<div id="ref-Morey2011" class="csl-entry" role="listitem">
Morey, R. D., &amp; Rouder, J. N. (2011). Bayes factor approaches for testing interval null hypotheses. <em>Psychological Methods</em>, <em>16</em>(4), 406–419. <a href="https://doi.org/10.1037/a0024377">https://doi.org/10.1037/a0024377</a>
</div>
<div id="ref-Müller2004" class="csl-entry" role="listitem">
Müller, P., Parmigiani, G., Robert, C., &amp; Rousseau, J. (2004). Optimal sample size for multiple testing. <em>Journal of the American Statistical Association</em>, <em>99</em>(468), 990–1001. <a href="https://doi.org/10.1198/016214504000001646">https://doi.org/10.1198/016214504000001646</a>
</div>
<div id="ref-Hagan2019" class="csl-entry" role="listitem">
O’Hagan, A. (2019). Expert knowledge elicitation: Subjective but scientific. <em>The American Statistician</em>, <em>73</em>(sup1), 69–81. <a href="https://doi.org/10.1080/00031305.2018.1518265">https://doi.org/10.1080/00031305.2018.1518265</a>
</div>
<div id="ref-Pfadt2025" class="csl-entry" role="listitem">
Pfadt, J. M., Bartoš, F., Godmann, H. R., Waaijers, M., Groot, L., Heo, I., et al. (2025, October 30). <em>A methodological metamorphosis: The rapid rise of bayesian inference and open science practices in psychology</em>. OSF Preprints. <a href="https://doi.org/10.31234/osf.io/ck3js_v1">https://doi.org/10.31234/osf.io/ck3js_v1</a>
</div>
<div id="ref-Pruzek2016" class="csl-entry" role="listitem">
Pruzek, R. M. (2016). <em>An introduction to bayesian inference and its applications</em> (pp. 305–334). Routledge.
</div>
<div id="ref-Rubin1984" class="csl-entry" role="listitem">
Rubin, D. B. (1984). Bayesianly justifiable and relevant frequency calculations for the applied statistician. <em>The Annals of Statistics</em>, <em>12</em>(4), 1151–1172. <a href="https://doi.org/10.1214/aos/1176346785">https://doi.org/10.1214/aos/1176346785</a>
</div>
<div id="ref-Schnell2020" class="csl-entry" role="listitem">
Schnell, P. M., Fiecas, M., &amp; Carlin, B. P. (2020). <span><strong>credsubs</strong></span> : Multiplicity-adjusted subset identification. <em>Journal of Statistical Software</em>, <em>94</em>(7). <a href="https://doi.org/10.18637/jss.v094.i07">https://doi.org/10.18637/jss.v094.i07</a>
</div>
<div id="ref-Schnell2016" class="csl-entry" role="listitem">
Schnell, P. M., Tang, Q., Offen, W. W., &amp; Carlin, B. P. (2016). A Bayesian Credible Subgroups Approach to Identifying Patient Subgroups with Positive Treatment Effects. <em>Biometrics</em>, <em>72</em>(4), 1026–1036. <a href="https://doi.org/10.1111/biom.12522">https://doi.org/10.1111/biom.12522</a>
</div>
<div id="ref-Schurr2024" class="csl-entry" role="listitem">
Schurr, R., Reznik, D., Hillman, H., Bhui, R., &amp; Gershman, S. J. (2024). Dynamic computational phenotyping of human cognition. <em>Nature Human Behaviour</em>, <em>8</em>(5), 917–931. <a href="https://doi.org/10.1038/s41562-024-01814-x">https://doi.org/10.1038/s41562-024-01814-x</a>
</div>
<div id="ref-Scott2006" class="csl-entry" role="listitem">
Scott, J. G., &amp; Berger, J. O. (2006). An exploration of aspects of bayesian multiple testing. <em>Journal of Statistical Planning and Inference</em>, <em>136</em>(7), 2144–2162.
</div>
<div id="ref-Scott2010" class="csl-entry" role="listitem">
Scott, J. G., &amp; Berger, J. O. (2010). <span class="nocase">Bayes and empirical-Bayes multiplicity adjustment in the variable-selection problem</span>. <em>The Annals of Statistics</em>, <em>38</em>(5), 2587–2619. <a href="https://doi.org/10.1214/10-AOS792">https://doi.org/10.1214/10-AOS792</a>
</div>
<div id="ref-Shaffer1995" class="csl-entry" role="listitem">
Shaffer, J. P. (1995). Multiple hypothesis testing. <em>Annual Review of Psychology</em>, <em>46</em>, 561–584. <a href="https://doi.org/10.1146/annurev.ps.46.020195.003021">https://doi.org/10.1146/annurev.ps.46.020195.003021</a>
</div>
<div id="ref-Shi2021" class="csl-entry" role="listitem">
Shi, H., &amp; Yin, G. (2021). Reconnecting p-value and posterior probability under one- and two-sided tests. <em>The American Statistician</em>, <em>75</em>(3), 265–275. <a href="https://doi.org/10.1080/00031305.2020.1717621">https://doi.org/10.1080/00031305.2020.1717621</a>
</div>
<div id="ref-Singmann2016" class="csl-entry" role="listitem">
Singmann, H., Bolker, B., Westfall, J., &amp; Aust, F. (2016). <em>Afex: Analysis of factorial experiments</em>. <a href="https://CRAN.R-project.org/package=afex">https://CRAN.R-project.org/package=afex</a>
</div>
<div id="ref-Stephens2017" class="csl-entry" role="listitem">
Stephens, M. (2017). False discovery rates: A new deal. <em>Biostatistics (Oxford, England)</em>, <em>18</em>(2), 275–294. <a href="https://doi.org/10.1093/biostatistics/kxw041">https://doi.org/10.1093/biostatistics/kxw041</a>
</div>
<div id="ref-Stone2024" class="csl-entry" role="listitem">
Stone-Sabali, S., Uanhoro, J. O., McClain, S., Bernard, D., Makari, S., &amp; Chapman-Hilliard, C. (2024). Impostorism and <span>Psychological Distress</span> among <span>College Students</span> of <span>Color</span>: <span>A</span> moderation analysis of <span class="nocase">Shame-proneness</span>, <span>Race</span>, <span>Gender</span>, and <span>Race-Gender Interactions</span>. <em>Current Psychology</em>, <em>43</em>(4), 3632–3648. <a href="https://doi.org/10.1007/s12144-023-04579-0">https://doi.org/10.1007/s12144-023-04579-0</a>
</div>
<div id="ref-Storey2002" class="csl-entry" role="listitem">
Storey, J. D. (2002). A direct approach to false discovery rates. <em>Journal of the Royal Statistical Society: Series B (Statistical Methodology)</em>, <em>64</em>(3), 479–498. <a href="https://doi.org/10.1111/1467-9868.00346">https://doi.org/10.1111/1467-9868.00346</a>
</div>
<div id="ref-Storey2003" class="csl-entry" role="listitem">
Storey, J. D. (2003). The positive false discovery rate: A bayesian interpretation and the q-value. <em>The Annals of Statistics</em>, <em>31</em>(6), 2013–2035. <a href="https://doi.org/10.1214/aos/1074290335">https://doi.org/10.1214/aos/1074290335</a>
</div>
<div id="ref-Tendeiro2019" class="csl-entry" role="listitem">
Tendeiro, J. N., &amp; Kiers, H. A. (2019). A review of issues about null hypothesis bayesian testing. <em>Psychological Methods</em>, <em>24</em>(6), 774. <a href="https://doi.org/10.1037/met0000221">https://doi.org/10.1037/met0000221</a>
</div>
<div id="ref-Tendeiro2024" class="csl-entry" role="listitem">
Tendeiro, J. N., Kiers, H. A., Hoekstra, R., Wong, T. K., &amp; Morey, R. D. (2024). Diagnosing the misuse of the bayes factor in applied research. <em>Advances in Methods and Practices in Psychological Science</em>, <em>7</em>(1), 25152459231213371. <a href="https://doi.org/10.1177/25152459231213371">https://doi.org/10.1177/25152459231213371</a>
</div>
<div id="ref-Van2017" class="csl-entry" role="listitem">
Van De Schoot, R., Winter, S. D., Ryan, O., Zondervan-Zwijnenburg, M., &amp; Depaoli, S. (2017). A systematic review of bayesian articles in psychology: The last 25 years. <em>Psychological Methods</em>, <em>22</em>(2), 217. <a href="https://doi.org/10.1037/met0000100">https://doi.org/10.1037/met0000100</a>
</div>
<div id="ref-Bergh2020" class="csl-entry" role="listitem">
van den Bergh, D., van Doorn, J., Marsman, M., Draws, T., van Kesteren, E.-J., Derks, K., Dablander, F., Gronau, Q. F., Kucharský, Š., Gupta, A. R. K. N., Sarafoglou, A., Voelkel, J. G., Stefan, A., Ly, A., Hinne, M., Matzke, D., &amp; Wagenmakers, E.-J. (2020). A tutorial on conducting and interpreting a <span>Bayesian ANOVA</span> in <span>JASP</span>. <em>L’Année Psychologique</em>, <em>120</em>(1), 73–96. <a href="https://doi.org/10.3917/anpsy1.201.0073">https://doi.org/10.3917/anpsy1.201.0073</a>
</div>
<div id="ref-Ventz2015" class="csl-entry" role="listitem">
Ventz, S., &amp; Trippa, L. (2015). Bayesian Designs and the Control of Frequentist Characteristics: A Practical Solution. <em>Biometrics</em>, <em>71</em>(1), 218–226. <a href="https://doi.org/10.1111/biom.12226">https://doi.org/10.1111/biom.12226</a>
</div>
<div id="ref-Westfall1997" class="csl-entry" role="listitem">
Westfall, P. H., Johnson, W. O., &amp; Utts, J. M. (1997). A bayesian perspective on the bonferroni adjustment. <em>Biometrika</em>, <em>84</em>(2), 419–427. <a href="https://doi.org/10.1093/biomet/84.2.419">https://doi.org/10.1093/biomet/84.2.419</a>
</div>
<div id="ref-Westfall2011" class="csl-entry" role="listitem">
Westfall, P. H., Tobias, R. D., &amp; Wolfinger, R. D. (2011). <em>Multiple comparisons and multiple tests using <span>SAS</span>, second edition</em>. SAS Institute. <a href="https://doi.org/10.1002/sim.1168">https://doi.org/10.1002/sim.1168</a>
</div>
<div id="ref-Westfall1993" class="csl-entry" role="listitem">
Westfall, P. H., &amp; Young, S. S. (1993). <em>Resampling-based multiple testing: Examples and methods for p-value adjustment</em>. Wiley. <a href="https://doi.org/10.2307/2348369">https://doi.org/10.2307/2348369</a>
</div>
<div id="ref-Zhang2019" class="csl-entry" role="listitem">
Zhang, Y., Trippa, L., &amp; Parmigiani, G. (2019). Frequentist operating characteristics of Bayesian optimal designs via simulation. <em>Statistics in Medicine</em>, <em>38</em>(21), 4026–4039. <a href="https://doi.org/10.1002/sim.8279">https://doi.org/10.1002/sim.8279</a>
</div>
<div id="ref-Zwet2021" class="csl-entry" role="listitem">
Zwet, E. van, &amp; Cator, E. A. (2021). The significance filter, the winner’s curse and the need to shrink. <em>Statistica Neerlandica</em>, <em>75</em>(4), 437–452. <a href="https://doi.org/10.1111/stan.12241">https://doi.org/10.1111/stan.12241</a>
</div>
<div id="ref-Zwet2022" class="csl-entry" role="listitem">
Zwet, E. van, &amp; Gelman, A. (2022). A proposal for informative default priors scaled by the standard error of estimates. <em>The American Statistician</em>, <em>76</em>(1), 1–9. <a href="https://doi.org/10.1080/00031305.2021.1938225">https://doi.org/10.1080/00031305.2021.1938225</a>
</div>
</div>
<div class="cell FigureWithoutNote" data-layout-align="left" data-custom-style="FigureWithoutNote">
<div class="cell-output-display">
<div id="fig-pd-ci" class="quarto-float quarto-figure quarto-figure-left" data-fignum="1" prefix="" data-fig-align="left">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-pd-ci-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Figure&nbsp;1</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p>Posterior distributions illustrating the relationship between the probability of direction (pd) and 95% Credible Interval (CI), using c = 0.975 and <span class="math inline">\theta_{null} = 0</span>.</p>
</div>
</figcaption>
<div aria-describedby="fig-pd-ci-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="manuscript_files/figure-html/fig-pd-ci-1.svg" class="img-fluid quarto-figure quarto-figure-left figure-img" width="3000">
</div>
</figure>
</div>
</div>
</div>
<div class="cell FigureWithoutNote" data-layout-align="left" data-custom-style="FigureWithoutNote">
<div class="cell-output-display">
<div id="fig-uniform-pd" class="quarto-float quarto-figure quarto-figure-left" data-fignum="2" prefix="" data-fig-align="left">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-uniform-pd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Figure&nbsp;2</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p>Distribution of the probability of direction (pd) stratified by sample size (<span class="math inline">n = 30, 50, 100</span>; rows) and prior standard deviation (<span class="math inline">\theta \sim \mathcal{N}(0, \tau)</span> with <span class="math inline">\tau \in \{0.2, 0.5, 1, 1.5\}</span>; columns). Bin width = 0.025.</p>
</div>
</figcaption>
<div aria-describedby="fig-uniform-pd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="manuscript_files/figure-html/fig-uniform-pd-1.svg" class="img-fluid quarto-figure quarto-figure-left figure-img" width="3600">
</div>
</figure>
</div>
</div>
</div>
<div class="cell FigureWithoutNote" data-layout-align="left" data-custom-style="FigureWithoutNote">
<div class="cell-output-display">
<div id="fig-prior-adj" class="quarto-float quarto-figure quarto-figure-left" data-fignum="3" prefix="" data-fig-align="left">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-prior-adj-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Figure&nbsp;3</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p>Relationship between the global-null probability, the implied prior probability assigned to individual hypotheses, and the resulting adjustment of the probability of direction (pd). The left panel shows how a specified probability that all tested effects are null, <span class="math inline">\Pr(H0)</span>, translates into the prior probability <span class="math inline">\pi_0</span> assigned to each individual hypothesis. As the number of tested effects (m) increases, the same global-null assumption implies increasingly skeptical priors for individual tests. The dotted line marks <span class="math inline">\pi_0 = 0.5</span>, below which the prior would favor the alternative hypothesis rather than the null. Because our goal is to introduce a conservative multiplicity adjustment, <span class="math inline">\pi_0</span> is capped at 0.5 whenever smaller values would arise. The right panel illustrates the practical consequences of this adjustment. For a given <span class="math inline">\pi_0</span>, the adjusted probability of direction (<span class="math inline">pd_{adj}</span>) is always smaller than or equal to the original pd, but the reduction is not uniform. Weak evidence is penalized much more strongly than strong evidence.</p>
</div>
</figcaption>
<div aria-describedby="fig-prior-adj-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="manuscript_files/figure-html/fig-prior-adj-1.svg" class="img-fluid quarto-figure quarto-figure-left figure-img" width="3000">
</div>
</figure>
</div>
</div>
</div>
<div class="cell FigureWithoutNote" data-layout-align="left" data-custom-style="FigureWithoutNote">
<div class="cell-output-display">
<div id="fig-ind-fdr-pw" class="quarto-float quarto-figure quarto-figure-left" data-fignum="4" prefix="" data-fig-align="left">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-ind-fdr-pw-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Figure&nbsp;4</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p>False Discovery Rate (FDR, Panel A) and average power (Panel B) of the adjusted <span class="math inline">pd</span> procedure as a function of the specified per-test null prior <span class="math inline">\pi_0</span> (x-axis) and the true null probability <span class="math inline">\pi_{0_{true}}</span> (y-axis), by family size m (rows, for Panel A) and sample size n (columns). The column <span class="math inline">\pi_0 = 0.5</span> is the unadjusted rule, where the prior odds are one and no correction is applied (<span class="math inline">pd_{adj} = pd</span>); the diagonal <span class="math inline">\pi_0 = \pi_{0_{true}}</span> is a correctly specified prior. Each cell is the empirical FDR/power over 10,000 replications.</p>
</div>
</figcaption>
<div aria-describedby="fig-ind-fdr-pw-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="manuscript_files/figure-html/fig-ind-fdr-pw-1.svg" class="img-fluid quarto-figure quarto-figure-left figure-img" width="6300">
</div>
</figure>
</div>
</div>
</div>
<div class="cell FigureWithoutNote" data-layout-align="left" data-custom-style="FigureWithoutNote">
<div class="cell-output-display">
<div id="fig-ind-fwer" class="quarto-float quarto-figure quarto-figure-left" data-fignum="5" prefix="" data-fig-align="left">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-ind-fwer-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Figure&nbsp;5</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p>Family-wise error rate (FWER) of the adjusted <span class="math inline">pd</span> procedure as a function of the specified per-test null prior <span class="math inline">\pi_0</span> (x-axis) and the true null probability <span class="math inline">\pi_{0_{true}}</span> (y-axis), by family size m (columns). The column <span class="math inline">\pi_0 = 0.5</span> is the unadjusted rule. Each cell is the empirical FWER over 10,000 replications. Because the per-test adjustment targets the FDR, the FWER is reduced by larger <span class="math inline">\pi_0</span> but still grows with the family size <span class="math inline">m</span>.</p>
</div>
</figcaption>
<div aria-describedby="fig-ind-fwer-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="manuscript_files/figure-html/fig-ind-fwer-1.svg" class="img-fluid quarto-figure quarto-figure-left figure-img" width="6600">
</div>
</figure>
</div>
</div>
</div>
<div class="cell FigureWithoutNote" data-layout-align="center" data-custom-style="FigureWithoutNote">
<div class="cell-output-display">
<div id="fig-compare" class="quarto-float quarto-figure quarto-figure-center" data-fignum="6" prefix="" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-compare-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Figure&nbsp;6</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p>False Discovery Rate (FDR), Family-Wise Error Rate (FWER) and average power of three Bayesian rules as a function of the number of tests <span class="math inline">m</span>, all at <span class="math inline">\alpha = 0.05</span>: the prior-odds procedure (adjusted <span class="math inline">pd &gt; 0.975</span>, <span class="math inline">\pi_0 = 0.7</span>), joint statements (strongest directional claims accepted while their joint probability is at least <span class="math inline">0.95</span>), and simultaneous credible intervals (<span class="math inline">95\%</span> band excluding zero). Sample size <span class="math inline">n = 50</span>; 10,000 replications per cell.</p>
</div>
</figcaption>
<div aria-describedby="fig-compare-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="manuscript_files/figure-html/fig-compare-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img" width="4800">
</div>
</figure>
</div>
</div>
</div>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Although frequentist and Bayesian frameworks rest on different foundations, examining the frequentist operating characteristics of a Bayesian procedure (how it behaves over repeated use) is a well-established practice <span class="citation" data-cites="Zhang2019 Ventz2015 Müller2004">(<a href="#ref-Müller2004" role="doc-biblioref">Müller et al., 2004</a>; <a href="#ref-Ventz2015" role="doc-biblioref">Ventz &amp; Trippa, 2015</a>; <a href="#ref-Zhang2019" role="doc-biblioref">Zhang et al., 2019</a>)</span>. This perspective treats long-run performance as a useful diagnostic for Bayesian inference <span class="citation" data-cites="Rubin1984 GelmanBook">(<a href="#ref-GelmanBook" role="doc-biblioref">Gelman et al., 2013</a>; <a href="#ref-Rubin1984" role="doc-biblioref">Rubin, 1984</a>)</span>.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>